# Forecasting GDP Growth
This project tasks you with forecasting quarterly nominal GDP growth rate in the United States. The dataset contains estimated nominal gross domestic product (GDP) annual growth rate in each quarter from 1990 to 2020, released by the Bureau of Economic Analysis (BEA) of the United States Department of Commerce. The estimate is the “third” or "final" estimate of GDP issued in the third month after the relevant quarter which is based on more complete source data than were available for the "second" estimate issued in the second month and the "advance" estimate issued in the first month after the relevant quarter. You may refer to the [BEA website](https://www.bea.gov/resources/learning-center/what-to-know-gdp) for more information on the estimate of GDP in the United States. You will train models to forecast the BEA's final GDP estimate for a quarter. Specifically you are required to answer this question: Is accounting information useful for GDP forecast? You will be allowed to use any outside data to build your model.

The evaluation pages describes how submissions will be scored and how students should format their submissions. --- The evaluation metric for this competition is [RMSE](https://en.wikipedia.org/wiki/Root-mean-square_deviation). RMSE is a measure of the accuracy of your predictions.

**Files**
- GDP_Forecast_train.csv - the training set
- GDP_Forecast_test.csv - the test set
- GDP_Forecast_sampleSubmission.csv - a sample submission file in the correct format

**Columns**
- YQ - The year and quarter variable. 1990Q1 refers to the first calendar quarter of 1990, ie, Jan - March 1990
- NGDP - nominal GDP growth rate in the quarter of the year. It is obtained from the BEA final estimate which is available at the BEA website.

**Features** (no features data provided)

Following Datar et al. (2020), you may consider the following data as your predictors/features:
- Accounting data - through COMPUSTAT on WRDS
- Stock price/return data - through CRSP on WRDS
- Analysts' forecast of GDP - through Survey of Professional Forecasters
- Any other data

In [94]:
import pandas as pd

train = pd.read_csv("data/GDP_Forecast_train.csv")
test = pd.read_csv("data/GDP_Forecast_test.csv")

In [95]:
def create_submission(test_df, y_pred, filename):
    df = pd.DataFrame({"YQ": test_df["YQ"], "NGDP": y_pred})
    df.to_csv(f"attempts/{filename}.csv", index = False)

In [96]:
# splitting year-quarter to check for traits in yearly patterns vs quarterly pattern

# ensure year is an integer
train["year"] = train["YQ"].str[:4].astype(int)
test["year"] = test["YQ"].str[:4].astype(int)
# keep qtr as string / category
train["qtr"] = train["YQ"].str[4:]
test["qtr"] = test["YQ"].str[4:]
train.head()

       YQ  NGDP  year qtr
0  1990Q1   9.0  1990  Q1
1  1990Q2   6.1  1990  Q2
2  1990Q3   3.7  1990  Q3
3  1990Q4  -0.7  1990  Q4
4  1991Q1   2.0  1991  Q1

### Base model for reference

In [97]:
import statsmodels.formula.api as smf

# running base linear model
base_model = smf.ols("NGDP ~ year + qtr", train).fit()
# printing summary of base_model
print(base_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.118
Model:                            OLS   Adj. R-squared:                  0.083
Method:                 Least Squares   F-statistic:                     3.324
Date:                Tue, 03 Mar 2026   Prob (F-statistic):             0.0134
Time:                        15:36:22   Log-Likelihood:                -244.91
No. Observations:                 104   AIC:                             499.8
Df Residuals:                      99   BIC:                             513.0
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    219.8404     68.424      3.213      0.002      84.073     355.608
qtr[T.Q2]      1.3038      0.725      1.799      0.075      -0.134       2.742
qtr[T.Q3]      0.5692      0.725      0.785      0.434      -0.869       2.007
qtr[T.Q4]      0.4423      0.725      0.610      0.543      -0.996       1.881
year          -0.1078      0.034     -3.154      0.002      -0.176      -0.040
==============================================================================
Omnibus:                       34.201   Durbin-Watson:                   1.137
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               83.130
Skew:                          -1.210   Prob(JB):                     8.88e-19
Kurtosis:                       6.651   Cond. No.                     5.35e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.35e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [98]:
import numpy as np
from sklearn.metrics import mean_squared_error

# get predicted values based off model
y_pred = base_model.predict(test)
y_true = test["NGDP"]
create_submission(test, y_pred, "0_base_forecast")
# evaluate using RMSE:
print(f"RMSE: {np.sqrt(mean_squared_error(y_true, y_pred))}")

RMSE: 2.96495609125275

Interpretation: To be discussed

### How Accounting Data affects GDP (COMPUSTAT on WRDS)
- [Compustat North America](https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/north-america-daily/) is a database of U.S. and Canadian fundamental and market information on active and inactive publicly held companies. It provides more than 300 annual and 100 quarterly Income Statement, Balance Sheet, Statement of Cash Flows, and supplemental data items. For most companies, annual history is available back to 1950 and quarterly history back to 1962 with monthly market history back to 1962.
- To consider [Execucomp](https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/execucomp/): Executive compensation data collected directly from each company’s annual proxy (DEF14A SEC form)

In [ ]:
# Using Compustat North America: Fundamentals Quarterly
# https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/north-america-daily/fundamentals-quarterly/
# NOTE: currency in USD, data in STD format

compustat = pd.read_csv("data/compustat_quarterly_financials.csv")
## dropping columns with no unique data
compustat.drop(columns = ["curcdq", "datafmt", "indfmt", "consol"], inplace = True)
## dropping columns without too many missing data
# print(compustat[compustat["ltq"].notna()].shape) # 26666 out of 85349
compustat.drop(columns = ["ltq"], inplace = True)
## droping costat - only 2 options
compustat.drop(columns = ["costat"], inplace = True)
compustat.head()

   gvkey    datadate                        conm datacqtr       atq    niq
0   1178  1990-03-31  AFFILIATED BANKSHARES COLO   1990Q1  2597.647  2.445
1   1178  1990-06-30  AFFILIATED BANKSHARES COLO   1990Q2  2645.271  3.234
2   1178  1990-09-30  AFFILIATED BANKSHARES COLO   1990Q3  2682.906  3.253
3   1178  1990-12-31  AFFILIATED BANKSHARES COLO   1990Q4  2738.097  0.897
4   1178  1991-03-31  AFFILIATED BANKSHARES COLO   1991Q1  2655.894  3.536

** NOTE TO DISCUSS, REMOVE COSTAT OR NO

In [100]:
print("total values present:")
print(f"total shape: {compustat.shape}")
print(f"datadate: {compustat[compustat["datadate"].notna()].shape[0]}\
        conm: {compustat[compustat["conm"].notna()].shape[0]}\
        datacqtr: {compustat[compustat["datacqtr"].notna()].shape[0]}")
print(f"atq: {compustat[compustat["atq"].notna()].shape[0]}\
        niq: {compustat[compustat["niq"].notna()].shape[0]}")

total values present:
total shape: (98258, 6)
datadate: 98258        conm: 98258        datacqtr: 98258
atq: 83551        niq: 85553

- (gvkey) Global Company Key
- (conm) Company Name
- (datacqtr) Calendar Data Year and Quarter
- (atq) Assets - Total
- (ltq) Liabilities - Total
- (niq) Net Income (Loss)

In [101]:
train_comp_macro = train.merge(compustat, how = "left", left_on = "YQ", right_on = "datacqtr")
test_comp_macro = test.merge(compustat, how = "left", left_on = "YQ", right_on = "datacqtr")
train_comp_macro.head()

,YQ,NGDP,year,qtr,gvkey,datadate,conm,datacqtr,atq,niq
0,1990Q1,9.0,1990,Q1,1178,1990-03-31,AFFILIATED BANKSHARES COLO,1990Q1,2597.647,2.445
1,1990Q1,9.0,1990,Q1,1194,1990-03-31,AHMANSON (H F) & CO,1990Q1,45984.500,65.978
2,1990Q1,9.0,1990,Q1,1416,1990-03-31,AMERICAN CAPITAL CORP,1990Q1,5257.766,NaN
3,1990Q1,9.0,1990,Q1,1553,1990-03-31,AMERICAN SVGS/FL FSB,1990Q1,NaN,0.698
4,1990Q1,9.0,1990,Q1,3431,1990-03-31,CONSTELLATION BANCORP,1990Q1,NaN,NaN

In [102]:
# creating model with accounting macro data
# no need to model gvkey and conm on the same model
comp_macro_model = smf.ols("NGDP ~ year + qtr + conm + atq + niq", train_comp_macro).fit()
# printing summary of comp_macro_model
print(comp_macro_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.156
Model:                            OLS   Adj. R-squared:                  0.130
Method:                 Least Squares   F-statistic:                     6.103
Date:                Tue, 03 Mar 2026   Prob (F-statistic):               0.00
Time:                        15:36:52   Log-Likelihood:            -1.6624e+05
No. Observations:               71262   AIC:                         3.367e+05
Df Residuals:                   69166   BIC:                         3.559e+05
Df Model:                        2095
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                              279.6362      4.345     64.365      0.000     271.121     288.152
qtr[T.Q2]                                1.3376      0.027     49.518      0.000       1.285       1.391
qtr[T.Q3]                                0.5943      0.027     21.947      0.000       0.541       0.647
qtr[T.Q4]                                0.6693      0.027     24.972      0.000       0.617       0.722
conm[T.1ST BERGEN BANCORP]               0.5520      1.002      0.551      0.582      -1.411       2.515
conm[T.1ST CAP BANCORP]                  0.5526      0.833      0.664      0.507      -1.079       2.185
conm[T.1ST CENTENNIAL BANCORP]           0.2842      0.706      0.403      0.687      -1.099       1.668
conm[T.1ST CENTURY BANCSHARES INC]      -0.5634      0.694     -0.812      0.417      -1.923       0.796
conm[T.1ST CONSTITUTION BANCORP]         0.0411      0.632      0.065      0.948      -1.197       1.279
conm[T.1ST ENTERPRISE BANK]              0.7117      0.833      0.855      0.393      -0.920       2.344
conm[T.1ST INDEPENDENCE FINL GROUP]      0.4514      0.646      0.699      0.485      -0.814       1.717
conm[T.1ST PACIFIC BANCORP]             -1.9427      0.866     -2.244      0.025      -3.640      -0.246
conm[T.1ST SOURCE CORP]                  0.0938      0.603      0.156      0.876      -1.088       1.276
conm[T.1ST STATE BANCORP INC]            0.5541      0.721      0.768      0.442      -0.860       1.968
conm[T.1ST UNITED BANCORP INC]          -0.8005      0.728     -1.100      0.271      -2.227       0.626
conm[T.1ST UTD BANCORP]                  0.2344      0.832      0.282      0.778      -1.396       1.865
conm[T.1ST WASHINGTON BANCORP INC]      -0.5242      0.935     -0.561      0.575      -2.357       1.308
conm[T.ABBEY NATL TREASURY SVCS PLC]     0.4214      1.377      0.306      0.760      -2.277       3.120
conm[T.ABIGAIL ADAMS NATL BANCORP]      -0.1437      0.623     -0.230      0.818      -1.365       1.078
conm[T.ABINGTON BANCORP INC]            -0.1674      0.702     -0.239      0.811      -1.542       1.208
conm[T.ABINGTON BANCORP INC-OLD]         0.1293      0.669      0.193      0.847      -1.182       1.441
conm[T.ABN-AMRO HOLDINGS NV]             0.3490      0.691      0.505      0.614      -1.006       1.704
conm[T.ABSA GROUP LTD]                   0.1200      0.722      0.166      0.868      -1.295       1.535
conm[T.ACADIANA BANCSHARES INC/LA]      -0.0597      0.740     -0.081      0.936      -1.510       1.391
conm[T.ACCESS ANYTIME BANCORP INC]       0.5481      0.659      0.832      0.405      -0.743       1.839
conm[T.ACCESS NATIONAL CORP]             0.2011      0.645      0.312      0.755      -1.062       1.464
conm[T.ACNB CORP]                       -0.0756      0.632     -0.120      0.905      -1.313       1.162
conm[T.ADIRONDACK TRUST CO]              0.0729      1.167      0.062      0.950      -2.214       2.360
conm[T.ADMIRALTY BANCORP INC]           -0.2146      0.832     -0.258      0.796      -1.845       1.416
conm[T.ADVANCE FINANCIAL BANCORP]        0.3028      0.697      0.435      0.664      -1.063       1.669
conm[T.ADVANTAGE BANCORP]                0.0863      0.817      0.106      0.916      -1.516       1.689
conm[T.AFFILIATED BANKSHARES COLO]      -1.4432      0.966     -1.495      0.135      -3.336       0.449
conm[T.AFFILIATED COMMUNITY BANCORP]     0.0907      0.848      0.107      0.915      -1.571       1.752
conm[T.AFFINITY BANCSHARES INC]         -0.4229      2.589     -0.163      0.870      -5.497       4.651
conm[T.AFSALA BANCORP INC]               0.2193      1.045      0.210      0.834      -1.829       2.268
conm[T.AHMANSON (H F) & CO]             -0.5174      0.693     -0.747      0.455      -1.875       0.840
conm[T.AIB GROUP PLC]                    0.2343      0.670      0.350      0.726      -1.078       1.547
conm[T.AJS BANCORP INC]                  0.3584      0.909      0.394      0.694      -1.424       2.141
conm[T.ALABAMA NATL BANCORPORATION]      0.4969      0.644      0.772      0.440      -0.765       1.759
conm[T.ALAMOGORDO FINANCIAL CORP]       -0.0457      0.805     -0.057      0.955      -1.623       1.531
conm[T.ALASKA PACIFIC BANCSHARS INC]    -0.1505      0.644     -0.234      0.815      -1.413       1.112
conm[T.ALBANK FINANCIAL CORP]            0.1706      0.782      0.218      0.827      -1.362       1.704
conm[T.ALBEMARLE FIRST BANK]             0.6160      0.772      0.797      0.425      -0.898       2.130
conm[T.ALBINA COMMUNITY BANCORP]        -1.0331      0.783     -1.320      0.187      -2.567       0.501
conm[T.ALBION BANC CORP]                 0.3120      0.747      0.418      0.676      -1.153       1.777
conm[T.ALERUS FINANCIAL CORP]           -0.3135      0.673     -0.466      0.641      -1.632       1.005
conm[T.ALLEGHENY BANCSHARES INC]        -1.7789      0.848     -2.097      0.036      -3.441      -0.117
conm[T.ALLEGHENY VALLEY BANCORP INC]    -0.3129      0.673     -0.465      0.642      -1.631       1.006
conm[T.ALLEGIANCE BANCORP INC]          -0.0991      0.965     -0.103      0.918      -1.991       1.793
conm[T.ALLEGIANT BANCORP INC]            0.1880      0.693      0.271      0.786      -1.170       1.546
conm[T.ALLFIRST FINANCIAL INC]          -0.3839      0.646     -0.594      0.552      -1.649       0.882
conm[T.ALLIANCE BANCORP INC]             0.2536      0.711      0.357      0.721      -1.139       1.646
conm[T.ALLIANCE BANCORP NEW ENGLAND]    -0.2512      0.637     -0.394      0.693      -1.500       0.997
conm[T.ALLIANCE BANCORP OF PA]           0.0895      0.609      0.147      0.883      -1.104       1.283
conm[T.ALLIANCE BANKSHARES CORP]         0.0121      0.670      0.018      0.986      -1.300       1.324
conm[T.ALLIANCE FINANCIAL CORP/NY]      -0.0485      0.636     -0.076      0.939      -1.295       1.198
conm[T.ALLIED BANK CAPITAL INC]         -0.2583      1.002     -0.258      0.797      -2.222       1.705
conm[T.ALLIED BANKSHARES INC/GA]        -0.0409      0.908     -0.045      0.964      -1.822       1.740
conm[T.ALTABANCORP]                      0.0449      1.167      0.038      0.969      -2.242       2.332
conm[T.AMB FINANCIAL CORP]               0.1354      0.610      0.222      0.824      -1.060       1.331
conm[T.AMBANC CORP]                      0.0947      0.793      0.119      0.905      -1.459       1.649
conm[T.AMBANC HOLDING CO INC]            0.1348      0.740      0.182      0.855      -1.316       1.585
conm[T.AMCORE FINANCIAL INC]            -0.0544      0.625     -0.087      0.931      -1.278       1.170
conm[T.AMEGY BANCORPORATION INC]         0.5605      0.685      0.818      0.413      -0.782       1.903
conm[T.AMERIANA BANCORP]                 0.1251      0.604      0.207      0.836      -1.058       1.308
conm[T.AMERIBANC INVESTORS GROUP]        0.7206      1.254      0.575      0.566      -1.738       3.179
conm[T.AMERICAN BANCORP NJ INC]          0.1221      0.734      0.166      0.868      -1.316       1.560
conm[T.AMERICAN BANCORP/NV]              0.0496      0.865      0.057      0.954      -1.647       1.746
conm[T.AMERICAN BANCORP/OH]              0.1442      0.701      0.206      0.837      -1.230       1.518
conm[T.AMERICAN BANCSHARES INC/FL]       0.7448      0.817      0.911      0.362      -0.858       2.347
conm[T.AMERICAN BANK CT WATERBURY]      -0.3144      0.654     -0.481      0.631      -1.596       0.967
conm[T.AMERICAN BANK INC/PA]             0.0703      0.650      0.108      0.914      -1.204       1.345
conm[T.AMERICAN BUSINESS BANK/CA]        0.5521      0.833      0.663      0.507      -1.080       2.184
conm[T.AMERICAN CAPITAL CORP]           -1.1868      0.772     -1.537      0.124      -2.701       0.327
conm[T.AMERICAN CMNTY BANCSHARES]       -0.0266      0.689     -0.039      0.969      -1.377       1.324
conm[T.AMERICAN FINANCIAL HLDGS INC]    -0.2328      0.866     -0.269      0.788      -1.929       1.464
conm[T.AMERICAN FSB GREENVILLE SC]       0.1500      0.848      0.177      0.860      -1.511       1.811
conm[T.AMERICAN NATIONAL BANCORP]        0.0151      1.002      0.015      0.988      -1.948       1.978
conm[T.AMERICAN NATL BANKSHARES]         0.0748      0.617      0.121      0.904      -1.135       1.284
conm[T.AMERICAN PACIFIC BANK  -CL B]     0.2051      0.656      0.313      0.755      -1.081       1.491
conm[T.AMERICAN RIVER BANKSHARES]        0.0155      0.625      0.025      0.980      -1.209       1.240
conm[T.AMERICAN RIVIERA BANCORP]        -0.4792      1.377     -0.348      0.728      -3.178       2.219
conm[T.AMERICAN SAVINGS BANK-NY]        -1.5987      1.002     -1.596      0.111      -3.562       0.365
conm[T.AMERICAN SVGS/FL FSB]            -1.1524      0.866     -1.331      0.183      -2.849       0.544
conm[T.AMERICANWEST BANCORP]             0.0054      0.631      0.009      0.993      -1.232       1.242
conm[T.AMERICASBANK CORP]                1.0379      0.886      1.172      0.241      -0.698       2.774
conm[T.AMERIFED FINANCIAL CORP]          0.1867      1.254      0.149      0.882      -2.272       2.645
conm[T.AMERIS BANCORP]                   0.0953      0.603      0.158      0.874      -1.087       1.277
conm[T.AMERISERV FINANCIAL INC/PA]       0.0955      0.603      0.158      0.874      -1.086       1.278
conm[T.AMERITRUST CORP-OLD]             -1.8365      1.099     -1.672      0.095      -3.990       0.317
conm[T.AMERN NATL SVGS BK FSB/MD]        0.0815      1.099      0.074      0.941      -2.072       2.235
conm[T.AMES NATIONAL CORP]              -0.0270      0.633     -0.043      0.966      -1.268       1.214
conm[T.AMFED FINANCIAL INC]             -0.1599      1.045     -0.153      0.878      -2.208       1.889
conm[T.AMITY BANCSHARES INC]            -0.1593      1.166     -0.137      0.891      -2.445       2.126
conm[T.AMSOUTH BANCORPORATION]           0.0619      0.622      0.099      0.921      -1.157       1.281
conm[T.AMTRUST CAPITAL CORP]             0.1443      0.832      0.174      0.862      -1.486       1.775
conm[T.ANB CORP]                         0.3115      0.747      0.417      0.677      -1.153       1.776
conm[T.ANCHOR BANCORP INC/NY]           -0.1626      1.166     -0.139      0.889      -2.448       2.123
conm[T.ANCHOR BANCORP WISCONSIN INC]     0.0806      0.605      0.133      0.894      -1.105       1.267
conm[T.ANCHOR BANCORP/WA]                0.2540      0.748      0.340      0.734      -1.212       1.720
conm[T.ANCHOR FINANCIAL CORP/SC]         0.7142      0.793      0.901      0.368      -0.840       2.268
conm[T.ANDOVER BANCORP INC/DE]           0.3046      0.706      0.432      0.666      -1.079       1.688
conm[T.ANNAPOLIS BANCORP INC]           -0.0397      0.631     -0.063      0.950      -1.277       1.198
conm[T.ANNAPOLIS BANCSHARES INC]        -0.2266      0.965     -0.235      0.814      -2.119       1.666
conm[T.ANZ GROUP HOLDINGS LIMITED]      -0.2142      0.671     -0.319      0.750      -1.530       1.101
conm[T.APPALACHIAN BANCSHARES INC]      -0.0613      0.734     -0.084      0.933      -1.499       1.377
conm[T.APPLE BANCORP INC]               -1.8929      1.376     -1.376      0.169      -4.590       0.804
conm[T.AREA BANCSHARES CORP]             0.1706      0.733      0.233      0.816      -1.267       1.608
conm[T.ARGENT BANK/LA]                   0.2342      0.832      0.282      0.778      -1.396       1.864
conm[T.ARGENTARIA CAJA POST BANC HP]     0.5448      0.909      0.600      0.549      -1.236       2.326
conm[T.ARIZONA COMMERCE BANK]           -0.1458      1.558     -0.094      0.925      -3.200       2.908
conm[T.ARROW FINANCIAL CORP]             0.0945      0.603      0.157      0.875      -1.087       1.276
conm[T.ASB BANCORP INC]                  0.5191      0.764      0.679      0.497      -0.979       2.017
conm[T.ASB FINANCIAL CORP]               0.4211      0.678      0.621      0.535      -0.908       1.751
conm[T.ASB HAWAII INC -SPN]              0.7438      1.870      0.398      0.691      -2.922       4.409
conm[T.ASPEN BANCSHARES INC]             0.0496      0.865      0.057      0.954      -1.647       1.746
conm[T.ASSOCIATED BANC-CORP]            -0.0399      0.596     -0.067      0.947      -1.209       1.129
conm[T.ASTORIA FINANCIAL CORP]           0.0909      0.603      0.151      0.880      -1.091       1.273
conm[T.ATHENS BANCSHARES CORP]          -0.2162      0.722     -0.299      0.765      -1.632       1.199
conm[T.ATLANFED BANCORP INC]             0.4314      1.376      0.314      0.754      -2.266       3.128
conm[T.ATLANTIC BANCGROUP INC]          -0.3144      0.667     -0.472      0.637      -1.621       0.992
conm[T.ATLANTIC CAP BANCSHARES INC]     -0.0981      1.255     -0.078      0.938      -2.558       2.362
conm[T.ATLANTIC CMNTY BANCORP INC]   -1.683e-15   2.37e-15     -0.711      0.477   -6.33e-15    2.96e-15
conm[T.ATLANTIC COAST FINANCIAL CP]      0.0780      0.648      0.120      0.904      -1.193       1.349
conm[T.ATLANTIC FINANCIAL CORP]          0.7895      0.818      0.966      0.334      -0.813       2.392
conm[T.ATLANTIC LIBERTY FINANCIAL]       1.3209      0.818      1.615      0.106      -0.282       2.924
conm[T.ATLANTIC SOUTHERN FINL GRP]      -0.6063      0.755     -0.803      0.422      -2.087       0.874
conm[T.ATLANTIC UNION BANKSHRS CRP]      0.0946      0.603      0.157      0.875      -1.087       1.277
conm[T.AUBURN BANCORP INC]              -0.8692      0.748     -1.162      0.245      -2.335       0.597
conm[T.AUBURN NATIONAL BANCORP]          0.1351      0.610      0.222      0.825      -1.060       1.330
conm[T.AVENUE FINANCIAL HOLDINGS]        0.3633      1.046      0.347      0.728      -1.687       2.413
conm[T.AVIDBANK HOLDINGS INC]            0.4362      0.783      0.557      0.577      -1.099       1.971
conm[T.AXOS FINANCIAL INC]               0.0323      0.652      0.049      0.961      -1.247       1.311
conm[T.B M J FINANCIAL CORP]            -0.0409      0.908     -0.045      0.964      -1.821       1.740
conm[T.BAKER BOYER BANCORP]              0.4351      1.099      0.396      0.692      -1.720       2.590
conm[T.BALTIMORE BANCORP]               -0.8864      0.793     -1.118      0.264      -2.440       0.668
conm[T.BANC OF CALIFORNIA INC]           0.0201      0.626      0.032      0.974      -1.207       1.247
conm[T.BANC OF CALIFORNIA INC -OLD]      0.0497      0.636      0.078      0.938      -1.197       1.296
conm[T.BANCFIRST CORP/OK]                0.0936      0.603      0.155      0.877      -1.088       1.276
conm[T.BANCFLORIDA FINANCIAL CORP]      -0.9890      0.818     -1.210      0.226      -2.591       0.613
conm[T.BANCO BBVA ARGENTINA SA]          0.0063      0.607      0.010      0.992      -1.183       1.195
conm[T.BANCO BILBAO VIZCAYA ARGENTA]    -0.3023      0.605     -0.500      0.617      -1.487       0.882
conm[T.BANCO CENTRAL HISPANO]           -0.6211      0.866     -0.718      0.473      -2.318       1.075
conm[T.BANCO COMERCIAL PORTUGUES SA]    -0.3836      0.672     -0.571      0.568      -1.701       0.933
conm[T.BANCO DE A EDWARDS SA]           -0.0414      0.866     -0.048      0.962      -1.738       1.655
conm[T.BANCO DE CHILE]                   0.0884      0.633      0.140      0.889      -1.152       1.329
conm[T.BANCO GALICIA BUENOS AIRES]       0.3414      0.716      0.477      0.633      -1.061       1.744
conm[T.BANCO ITAU CHILE]                -0.0004      0.657     -0.001      1.000      -1.288       1.287
conm[T.BANCO LATINOAMERICANO DE COM]     0.1304      0.607      0.215      0.830      -1.060       1.321
conm[T.BANCO MACRO SA]                  -0.2159      0.664     -0.325      0.745      -1.518       1.086
conm[T.BANCO SANTANDER ARGENTINA]        0.2511      0.866      0.290      0.772      -1.445       1.948
conm[T.BANCO SANTANDER BRASIL  -ADR]    -0.3391      0.723     -0.469      0.639      -1.755       1.077
conm[T.BANCO SANTANDER CHILE SA]         0.3715      0.818      0.454      0.650      -1.231       1.974
conm[T.BANCO SANTANDER MEXICO -ADR]      0.2890      0.866      0.334      0.739      -1.409       1.987
conm[T.BANCO SANTANDER SA]              -0.2123      0.613     -0.346      0.729      -1.414       0.990
conm[T.BANCO SANTANDER-CHILE]           -0.1661      0.636     -0.261      0.794      -1.413       1.080
conm[T.BANCOKLAHOMA CORP]               -1.9965      1.166     -1.712      0.087      -4.282       0.289
conm[T.BANCORP CONN INC]                 0.0654      0.693      0.094      0.925      -1.292       1.423
conm[T.BANCORP INC]                      0.1197      0.650      0.184      0.854      -1.155       1.394
conm[T.BANCORP NEW JERSEY INC]           0.3530      1.166      0.303      0.762      -1.932       2.638
conm[T.BANCORP OF NEW JERSEY INC]       -0.4427      0.682     -0.649      0.516      -1.780       0.895
conm[T.BANCORP RHODE ISLAND INC]        -0.1955      0.652     -0.300      0.764      -1.474       1.083
conm[T.BANCTRUST FINANCIAL GRP INC]      0.0220      0.613      0.036      0.971      -1.180       1.224
conm[T.BANCWEST CORP]                   -0.3719      0.648     -0.574      0.566      -1.641       0.898
conm[T.BANK FIRST CORP]                  0.5520      0.833      0.663      0.507      -1.080       2.184
conm[T.BANK HOLDINGS INC]               -0.0617      0.727     -0.085      0.932      -1.488       1.364
conm[T.BANK KY FINANCIAL CORP]           0.1062      0.624      0.170      0.865      -1.116       1.329
conm[T.BANK LOS ANGELES/CA]              0.4485      0.886      0.506      0.613      -1.287       2.184
conm[T.BANK MARYLAND CORP]               0.3533      1.166      0.303      0.762      -1.932       2.639
conm[T.BANK MUTUAL CORP]                 0.0193      0.626      0.031      0.975      -1.208       1.247
conm[T.BANK NEW HAMPSHIRE CORP]         -0.1598      1.045     -0.153      0.878      -2.208       1.889
conm[T.BANK OF AMERICA CORP]            -0.3367      0.608     -0.554      0.580      -1.528       0.854
conm[T.BANK OF BERMUDA LTD]              0.4521      1.166      0.388      0.698      -1.833       2.738
conm[T.BANK OF COMMERCE HOLDINGS]       -0.0754      0.632     -0.119      0.905      -1.313       1.162
conm[T.BANK OF COMMERCE SAN DIEGO]       0.2810      0.772      0.364      0.716      -1.233       1.795
conm[T.BANK OF FLORIDA CORP]            -0.1838      0.685     -0.268      0.789      -1.527       1.160
conm[T.BANK OF GRANITE CORP]            -0.0102      0.618     -0.016      0.987      -1.221       1.201
conm[T.BANK OF HAWAII CORP]             -0.1128      0.594     -0.190      0.849      -1.278       1.052
conm[T.BANK OF IRELAND GROUP PLC]        0.0891      0.689      0.129      0.897      -1.262       1.440
conm[T.BANK OF MARIN BANCORP]            0.0150      0.625      0.024      0.981      -1.210       1.240

Insights: Takes very long, and not what we want

In [103]:
compustat_macro = compustat.groupby("datacqtr").agg({"atq": "sum", "niq": "sum"}).reset_index()
# convert net income to percentage because GDP is growth rate
compustat_macro["atq_growth"] = compustat_macro["atq"].pct_change() * 100
compustat_macro["niq_growth"] = compustat_macro["niq"].pct_change() * 100
# converting infinite values to NaN
compustat_macro = compustat_macro.replace([np.inf, -np.inf], np.nan)
# creating a forensic lag
compustat_macro["niq_growth_lag1"] = compustat_macro["niq_growth"].shift(1)
compustat_macro["atq_growth_lag1"] = compustat_macro["atq_growth"].shift(1)
compustat_macro.head()

,datacqtr,atq,niq,atq_growth,niq_growth,niq_growth_lag1,atq_growth_lag1
0,1989Q4,0.000,0.000,NaN,NaN,NaN,NaN
1,1990Q1,3187273.043,4684.085,NaN,NaN,NaN,NaN
2,1990Q2,3412321.689,6396.105,7.060852,36.549721,NaN,NaN
3,1990Q3,3473969.743,3093.203,1.806631,-51.639271,36.549721,7.060852
4,1990Q4,3426461.019,-49.699,-1.367563,-101.606716,-51.639271,1.806631

In [104]:
# merging updated macro to train and test sets
train_comp_macro = train.merge(compustat_macro, left_on = "YQ", right_on = "datacqtr", how = "left")
test_comp_macro = test.merge(compustat_macro, left_on = "YQ", right_on = "datacqtr", how = "left")

In [105]:
# creating model with accounting cleaned macro data
comp_macro_model2 = smf.ols("NGDP ~ year + qtr + atq + niq \
                            + atq_growth + niq_growth \
                            + niq_growth_lag1 + atq_growth_lag1", train_comp_macro).fit()
# printing summary of comp_macro_model2
print(comp_macro_model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.396
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     5.967
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           6.76e-07
Time:                        15:36:53   Log-Likelihood:                -220.42
No. Observations:                 102   AIC:                             462.8
Df Residuals:                      91   BIC:                             491.7
Df Model:                          10
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         235.0200    256.495      0.916      0.362    -274.475     744.515
qtr[T.Q2]           0.8741      0.876      0.998      0.321      -0.866       2.615
qtr[T.Q3]           0.7098      0.643      1.104      0.273      -0.568       1.988
qtr[T.Q4]           1.5022      0.877      1.713      0.090      -0.239       3.244
year               -0.1158      0.129     -0.899      0.371      -0.371       0.140
atq              -6.92e-08   6.38e-08     -1.085      0.281   -1.96e-07    5.75e-08
niq              7.604e-05   1.29e-05      5.888      0.000    5.04e-05       0.000
atq_growth         -0.0385      0.020     -1.958      0.053      -0.078       0.001
niq_growth          0.0003      0.000      1.018      0.312      -0.000       0.001
niq_growth_lag1    -0.0001      0.000     -0.412      0.681      -0.001       0.000
atq_growth_lag1    -0.0378      0.020     -1.936      0.056      -0.077       0.001
==============================================================================
Omnibus:                        1.930   Durbin-Watson:                   1.801
Prob(Omnibus):                  0.381   Jarque-Bera (JB):                1.502
Skew:                          -0.289   Prob(JB):                        0.472
Kurtosis:                       3.141   Cond. No.                     2.74e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.74e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [106]:
# get predicted values based off model
y_pred2 = comp_macro_model2.predict(test_comp_macro)
y_true2 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred2, "1_acct_macro1_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781

**Stage 1**: removing atq (p-value: 0.281), niq_growth (p-value: 0.312) and niq_growth_lag1 (p-value: 0.681)

In [107]:
# creating model with accounting cleaned macro data
comp_macro_model3 = smf.ols("NGDP ~ year + qtr + niq + atq_growth + atq_growth_lag1", train_comp_macro).fit()
# printing summary of comp_macro_model3
print(comp_macro_model3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.378
Model:                            OLS   Adj. R-squared:                  0.332
Method:                 Least Squares   F-statistic:                     8.166
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           9.62e-08
Time:                        15:36:53   Log-Likelihood:                -221.91
No. Observations:                 102   AIC:                             459.8
Df Residuals:                      94   BIC:                             480.8
Df Model:                           7
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         488.4112     75.121      6.502      0.000     339.258     637.565
qtr[T.Q2]           1.1773      0.850      1.385      0.169      -0.510       2.865
qtr[T.Q3]           0.8194      0.635      1.291      0.200      -0.441       2.080
qtr[T.Q4]           1.7123      0.864      1.981      0.051      -0.004       3.428
year               -0.2431      0.038     -6.460      0.000      -0.318      -0.168
niq              7.886e-05   1.25e-05      6.298      0.000     5.4e-05       0.000
atq_growth         -0.0412      0.019     -2.165      0.033      -0.079      -0.003
atq_growth_lag1    -0.0300      0.019     -1.592      0.115      -0.067       0.007
==============================================================================
Omnibus:                        2.993   Durbin-Watson:                   1.702
Prob(Omnibus):                  0.224   Jarque-Bera (JB):                2.379
Skew:                          -0.343   Prob(JB):                        0.304
Kurtosis:                       3.300   Cond. No.                     1.31e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.31e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [108]:
# get predicted values based off model
y_pred3 = comp_macro_model3.predict(test_comp_macro)
y_true3 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred3, "2_acct_macro2_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))}")
print(f"RMSE w/ Accounting Macro V2: {np.sqrt(mean_squared_error(y_true3, y_pred3))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781
RMSE w/ Accounting Macro V2: 3.8884866286383355

Insights: improved RMSE, but not as good as Base

**Stage 2**: removing atq_growth_lag1 (p-value: 0.115)

In [109]:
# creating model with accounting cleaned macro data
comp_macro_model4 = smf.ols("NGDP ~ year + qtr + niq + atq_growth", train_comp_macro).fit()
# printing summary of comp_macro_model4
print(comp_macro_model4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.363
Model:                            OLS   Adj. R-squared:                  0.324
Method:                 Least Squares   F-statistic:                     9.133
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           6.69e-08
Time:                        15:36:53   Log-Likelihood:                -224.96
No. Observations:                 103   AIC:                             463.9
Df Residuals:                      96   BIC:                             482.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    482.9765     74.723      6.464      0.000     334.652     631.301
qtr[T.Q2]      1.7294      0.767      2.256      0.026       0.208       3.251
qtr[T.Q3]      0.9781      0.629      1.556      0.123      -0.270       2.226
qtr[T.Q4]      1.9202      0.856      2.243      0.027       0.221       3.619
year          -0.2406      0.037     -6.426      0.000      -0.315      -0.166
niq         7.628e-05   1.24e-05      6.129      0.000    5.16e-05       0.000
atq_growth    -0.0193      0.013     -1.461      0.147      -0.045       0.007
==============================================================================
Omnibus:                        3.179   Durbin-Watson:                   1.676
Prob(Omnibus):                  0.204   Jarque-Bera (JB):                2.587
Skew:                          -0.365   Prob(JB):                        0.274
Kurtosis:                       3.266   Cond. No.                     1.30e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [110]:
# get predicted values based off model
y_pred4 = comp_macro_model4.predict(test_comp_macro)
y_true4 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred4, "3_acct_macro3_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))}")
print(f"RMSE w/ Accounting Macro V2: {np.sqrt(mean_squared_error(y_true3, y_pred3))}")
print(f"RMSE w/ Accounting Macro V3: {np.sqrt(mean_squared_error(y_true4, y_pred4))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781
RMSE w/ Accounting Macro V2: 3.8884866286383355
RMSE w/ Accounting Macro V3: 3.638232349956233

Insights: improved RMSE, but still not as good as Base

**Stage 3**: removing atq_growth (p-value: 0.147)

In [111]:
# creating model with accounting cleaned macro data
comp_macro_model5 = smf.ols("NGDP ~ year + qtr + niq", train_comp_macro).fit()
# printing summary of comp_macro_model5
print(comp_macro_model5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.312
Method:                 Least Squares   F-statistic:                     10.33
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           5.63e-08
Time:                        15:36:53   Log-Likelihood:                -229.45
No. Observations:                 104   AIC:                             470.9
Df Residuals:                      98   BIC:                             486.8
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    485.4484     74.782      6.492      0.000     337.047     633.850
qtr[T.Q2]      0.9281      0.631      1.470      0.145      -0.324       2.181
qtr[T.Q3]      0.7116      0.628      1.132      0.260      -0.535       1.958
qtr[T.Q4]      0.9109      0.633      1.439      0.153      -0.345       2.167
year          -0.2415      0.037     -6.448      0.000      -0.316      -0.167
niq          7.18e-05   1.23e-05      5.825      0.000    4.73e-05    9.63e-05
==============================================================================
Omnibus:                        2.070   Durbin-Watson:                   1.625
Prob(Omnibus):                  0.355   Jarque-Bera (JB):                1.723
Skew:                          -0.313   Prob(JB):                        0.422
Kurtosis:                       3.072   Cond. No.                     1.28e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.28e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [112]:
# get predicted values based off model
y_pred5 = comp_macro_model5.predict(test_comp_macro)
y_true5 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred5, "4_acct_macro4_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))}")
print(f"RMSE w/ Accounting Macro V2: {np.sqrt(mean_squared_error(y_true3, y_pred3))}")
print(f"RMSE w/ Accounting Macro V3: {np.sqrt(mean_squared_error(y_true4, y_pred4))}")
print(f"RMSE w/ Accounting Macro V4: {np.sqrt(mean_squared_error(y_true5, y_pred5))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781
RMSE w/ Accounting Macro V2: 3.8884866286383355
RMSE w/ Accounting Macro V3: 3.638232349956233
RMSE w/ Accounting Macro V4: 3.3948414864271554

In [113]:
# creating model with accounting cleaned macro data
comp_macro_model6 = smf.ols("NGDP ~ year + niq", train_comp_macro).fit()
# printing summary of comp_macro_model6
print(comp_macro_model6.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.326
Model:                            OLS   Adj. R-squared:                  0.312
Method:                 Least Squares   F-statistic:                     24.40
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           2.26e-09
Time:                        15:36:53   Log-Likelihood:                -230.97
No. Observations:                 104   AIC:                             467.9
Df Residuals:                     101   BIC:                             475.9
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    484.9785     74.022      6.552      0.000     338.139     631.818
year          -0.2410      0.037     -6.500      0.000      -0.315      -0.167
niq          7.15e-05    1.2e-05      5.961      0.000    4.77e-05    9.53e-05
==============================================================================
Omnibus:                        2.396   Durbin-Watson:                   1.682
Prob(Omnibus):                  0.302   Jarque-Bera (JB):                1.886
Skew:                          -0.314   Prob(JB):                        0.389
Kurtosis:                       3.203   Cond. No.                     1.27e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.27e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [114]:
# get predicted values based off model
y_pred6 = comp_macro_model6.predict(test_comp_macro)
y_true6 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred6, "5_acct_macro5_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))}")
print(f"RMSE w/ Accounting Macro V2: {np.sqrt(mean_squared_error(y_true3, y_pred3))}")
print(f"RMSE w/ Accounting Macro V3: {np.sqrt(mean_squared_error(y_true4, y_pred4))}")
print(f"RMSE w/ Accounting Macro V4: {np.sqrt(mean_squared_error(y_true5, y_pred5))}")
print(f"RMSE w/ Accounting Macro without Quarter: {np.sqrt(mean_squared_error(y_true6, y_pred6))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781
RMSE w/ Accounting Macro V2: 3.8884866286383355
RMSE w/ Accounting Macro V3: 3.638232349956233
RMSE w/ Accounting Macro V4: 3.3948414864271554
RMSE w/ Accounting Macro without Quarter: 3.3808674839015227

Insights: after feeding output to Kaggle, it was recognised that
`atq + niq + atq_growth + niq_growth + niq_growth_lag1 + atq_growth_lag1`
performed the best even though its RMSE was highest

### How Stock Price / Return Data affects GDP (CRSP on WRDS)
1. Essential Variables (The "Core" Signal)
- (dlycaldt) Daily Calendar Date: daily moves into Year-Quarter (YQ) buckets
- (dlytotret) Daily Total Return on Index: This includes dividends. In forensic finance, this is the most powerful leading indicator. It represents the market's "real-time" discount of future economic growth.
- (dlytotval) Index Total Capitalization Value: This is the aggregate dollar value of all firms in the index. Use this to measure the Wealth Effect. If this value rises significantly, consumer spending (the biggest part of GDP) usually follows 1–2 quarters later.

2. Forensic Variables (To Lower Your RMSE)
- (dlytotind) Daily Index Level: Useful if you want to calculate the "momentum" of the market (e.g., comparing the current level to a 200-day moving average).
- (dlyincret) Daily Income Return on Index: This isolates the dividend component. A high income return relative to price return often signals a "flight to quality," which forensically precedes economic slowdowns.
- (dlyusdcnt) Used Count: The number of firms currently in the index. Rapid changes in the count of firms can signal structural shifts in the economy (like a wave of IPOs or bankruptcies).

In [115]:
# Using CRSP Daily Index and Portfolios on S&P 500
# https://wrds-www.wharton.upenn.edu/pages/get-data/center-research-security-prices-crsp/annual-update/index-version-2/daily-index-and-portfolios-on-sp-500/

crsp_daily_macro = pd.read_csv("data/crsp_snp500_indexes.csv")
## dropping columns with no unique data
# print(crsp_daily_macro[crsp_daily_macro["INDNO"] != 1000500].shape)
crsp_daily_macro.drop(columns = "INDNO", inplace = True)

## creating year, month and quarter identifiers
crsp_daily_macro["DlyCalDt"] = pd.to_datetime(crsp_daily_macro["DlyCalDt"])
crsp_daily_macro.set_index("DlyCalDt", inplace = True)
crsp_daily_macro

            DlyTotRet  DlyTotInd  DlyIncRet  DlyUsdCnt    DlyTotVal
DlyCalDt
1990-01-02   0.017527     633.75   0.000000        500   2371902979
1990-01-03  -0.002028     632.47   0.000020        500   2367046297
1990-01-04  -0.007913     627.46   0.000434        500   2347288970
1990-01-05  -0.010069     621.14   0.000023        500   2323602293
1990-01-08   0.004798     624.12   0.000088        500   2334547314
...               ...        ...        ...        ...          ...
2020-12-24   0.003623   12743.81   0.000103        505  32666322924
2020-12-28   0.008919   12857.47   0.000000        505  32957660480
2020-12-29  -0.002235   12828.73   0.000000        505  32884007696
2020-12-30   0.001484   12847.76   0.000111        505  32929142111
2020-12-31   0.006377   12929.70   0.000078        505  33142102780

[7812 rows x 5 columns]

In [116]:
## create quarterly data
crsp_qtr_macro = crsp_daily_macro.resample("Q").agg({
    "DlyTotRet": [
        ("qtr_ret", lambda x: (1+x).prod() - 1),    # compounded total return
        ("qtr_vola", "std")                         # quarterly volatility
    ],
    "DlyTotInd": [("qtr_index_level", "last")],     # final index level
    "DlyIncRet": [("qtr_income_ret", "sum")],       # total income return on index
    "DlyUsdCnt": [("avg_firm_count", "mean")]       # average number of firms
})

crsp_qtr_macro.columns = crsp_qtr_macro.columns.droplevel(0)
crsp_qtr_macro.reset_index(inplace = True)
## creating YQ column and moving it to first column
crsp_qtr_macro["YQ"] = crsp_qtr_macro["DlyCalDt"].dt.year.astype(str) + "Q" + crsp_qtr_macro["DlyCalDt"].dt.quarter.astype(str)
crsp_qtr_macro.drop(columns = "DlyCalDt", inplace = True)
col = crsp_qtr_macro.pop("YQ")
crsp_qtr_macro.insert(0, "YQ", col)
market_cols = "qtr_ret", "qtr_vola", "qtr_index_level", "qtr_income_ret", "avg_firm_count"
# creating last column market signals to predict current quarter
for col in market_cols: crsp_qtr_macro[f"{col}_lag1"] = crsp_qtr_macro[col].shift(1)
crsp_qtr_macro

C:\Users\sbgka\AppData\Local\Temp\ipykernel_5296\1514321405.py:2: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  crsp_qtr_macro = crsp_daily_macro.resample("Q").agg({

,YQ,qtr_ret,qtr_vola,qtr_index_level,qtr_income_ret,avg_firm_count,qtr_ret_lag1,qtr_vola_lag1,qtr_index_level_lag1,qtr_income_ret_lag1,avg_firm_count_lag1
0,1990Q1,-0.030222,0.008859,604.01,0.008371,499.984127,NaN,NaN,NaN,NaN,NaN
1,1990Q2,0.063453,0.007631,642.34,0.008977,500.000000,-0.030222,0.008859,604.01,0.008371,499.984127
2,1990Q3,-0.139556,0.011900,552.70,0.008717,499.984127,0.063453,0.007631,642.34,0.008977,500.000000
3,1990Q4,0.090365,0.011030,602.64,0.010018,500.000000,-0.139556,0.011900,552.70,0.008717,499.984127
4,1991Q1,0.147108,0.010541,691.30,0.008023,500.000000,0.090365,0.011030,602.64,0.010018,500.000000
...,...,...,...,...,...,...,...,...,...,...,...
119,2019Q4,0.089929,0.005923,10872.55,0.005012,505.000000,0.016904,0.009357,9975.45,0.005074,504.890625
120,2020Q1,-0.194095,0.035693,8762.26,0.005267,504.967742,0.089929,0.005923,10872.55,0.005012,505.000000
121,2020Q2,0.206679,0.019921,10573.22,0.004871,505.000000,-0.194095,0.035693,8762.26,0.005267,504.967742
122,2020Q3,0.089977,0.010664,11524.56,0.004149,505.000000,0.206679,0.019921,10573.22,0.004871,505.000000
123,2020Q4,0.121923,0.010263,12929.70,0.004153,504.921875,0.089977,0.010664,11524.56,0.004149,505.000000

When predicting GDP Growth, you are considering the last quarter's market signals

In [117]:
# merging updated macro to train and test sets
train_crsp_macro = train.merge(crsp_qtr_macro, on = "YQ", how = "left")
test_crsp_macro = test.merge(crsp_qtr_macro, on = "YQ", how = "left")

In [118]:
# creating model with cleaned macro data
crsp_macro_model1 = smf.ols("NGDP ~ year + qtr \
                            + qtr_ret + qtr_vola + qtr_index_level + \
                            qtr_income_ret + avg_firm_count \
                            + qtr_ret_lag1 + qtr_vola_lag1 + qtr_index_level_lag1 \
                            + qtr_income_ret_lag1 + avg_firm_count_lag1", train_crsp_macro).fit()
# printing summary of crsp_macro_model1
print(crsp_macro_model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.569
Model:                            OLS   Adj. R-squared:                  0.501
Method:                 Least Squares   F-statistic:                     8.304
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           4.87e-11
Time:                        15:36:53   Log-Likelihood:                -204.85
No. Observations:                 103   AIC:                             439.7
Df Residuals:                      88   BIC:                             479.2
Df Model:                          14
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               43.3631    441.129      0.098      0.922    -833.287     920.013
qtr[T.Q2]                1.5789      0.601      2.626      0.010       0.384       2.774
qtr[T.Q3]                1.0428      0.583      1.790      0.077      -0.115       2.201
qtr[T.Q4]                1.2074      0.689      1.753      0.083      -0.161       2.576
year                    -0.0835      0.076     -1.098      0.275      -0.235       0.068
qtr_ret                -11.6512      7.071     -1.648      0.103     -25.704       2.402
qtr_vola              -166.1565     68.882     -2.412      0.018    -303.046     -29.267
qtr_index_level          0.0058      0.003      2.151      0.034       0.000       0.011
qtr_income_ret        -720.8742    355.719     -2.027      0.046   -1427.791     -13.957
avg_firm_count          -1.0158      0.893     -1.137      0.259      -2.791       0.760
qtr_ret_lag1             0.9639      3.030      0.318      0.751      -5.057       6.985
qtr_vola_lag1         -110.4627     62.005     -1.782      0.078    -233.684      12.759
qtr_index_level_lag1    -0.0061      0.003     -2.171      0.033      -0.012      -0.001
qtr_income_ret_lag1     37.9759    356.359      0.107      0.915    -670.213     746.165
avg_firm_count_lag1      1.2853      1.359      0.946      0.347      -1.415       3.985
==============================================================================
Omnibus:                        0.205   Durbin-Watson:                   1.826
Prob(Omnibus):                  0.902   Jarque-Bera (JB):                0.276
Skew:                           0.103   Prob(JB):                        0.871
Kurtosis:                       2.852   Cond. No.                     1.24e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.24e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [119]:
# get predicted values based off model
y_pred7 = crsp_macro_model1.predict(test_crsp_macro)
y_true7 = test_crsp_macro["NGDP"]
create_submission(test_crsp_macro, y_pred7, "6_stocks_macro1_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))} (Best on Kaggle)")
print(f"RMSE w/ Stocks Macro: {np.sqrt(mean_squared_error(y_true7, y_pred7))}")

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781 (Best on Kaggle)
RMSE w/ Stocks Macro: 6.611278292423464

**Stage 1**: removing avg_firm_count (p-value: 0.259), avg_firm_count_lag1 (p-value: 0.347), qtr_ret_lag1 (p-value: 0.751), qtr_income_ret_lag1 (p-value: 0.915)

In [120]:
# creating model with cleaned macro data
crsp_macro_model2 = smf.ols("NGDP ~ year + qtr \
                            + qtr_ret + qtr_vola + qtr_index_level + qtr_income_ret \
                            + qtr_vola_lag1 + qtr_index_level_lag1", train_crsp_macro).fit()
# printing summary of crsp_macro_model2
print(crsp_macro_model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.562
Model:                            OLS   Adj. R-squared:                  0.514
Method:                 Least Squares   F-statistic:                     11.80
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           7.98e-13
Time:                        15:36:53   Log-Likelihood:                -205.71
No. Observations:                 103   AIC:                             433.4
Df Residuals:                      92   BIC:                             462.4
Df Model:                          10
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept              158.0987    131.452      1.203      0.232    -102.975     419.173
qtr[T.Q2]                1.4767      0.531      2.779      0.007       0.421       2.532
qtr[T.Q3]                0.9413      0.536      1.755      0.083      -0.124       2.007
qtr[T.Q4]                1.0472      0.569      1.840      0.069      -0.083       2.178
year                    -0.0733      0.066     -1.106      0.272      -0.205       0.058
qtr_ret                 -9.9113      6.654     -1.490      0.140     -23.127       3.304
qtr_vola              -168.6399     66.263     -2.545      0.013    -300.245     -37.035
qtr_index_level          0.0050      0.003      1.998      0.049    2.94e-05       0.010
qtr_income_ret        -715.4667    144.179     -4.962      0.000   -1001.819    -429.115
qtr_vola_lag1         -122.8357     54.936     -2.236      0.028    -231.944     -13.727
qtr_index_level_lag1    -0.0054      0.003     -2.095      0.039      -0.010      -0.000
==============================================================================
Omnibus:                        0.125   Durbin-Watson:                   1.831
Prob(Omnibus):                  0.940   Jarque-Bera (JB):                0.218
Skew:                           0.079   Prob(JB):                        0.897
Kurtosis:                       2.839   Cond. No.                     3.97e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.97e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [121]:
# get predicted values based off model
y_pred8 = crsp_macro_model2.predict(test_crsp_macro)
y_true8 = test_crsp_macro["NGDP"]
create_submission(test_crsp_macro, y_pred8, "7_stocks_macro2_forecast")

# evaluate using RMSE:
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))} (Best on Kaggle)")
print(f"RMSE w/ Stocks Macro: {np.sqrt(mean_squared_error(y_true7, y_pred7))}")
print(f"RMSE w/ Stocks Macro V2: {np.sqrt(mean_squared_error(y_true8, y_pred8))}")

# model with crsp stocks macro data

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781 (Best on Kaggle)
RMSE w/ Stocks Macro: 6.611278292423464
RMSE w/ Stocks Macro V2: 5.173724832298544

### Stop point: removing "year" as a parameter
It was recognised that throughout all models, year has a high p-value. It was recognised that year is insignificant as a predictor of GDP due to the test set containing data from 2020. In 2020, due to the COVID-19 pandemic, GDP significantly decreased across countries.

As such, this will not be a predictor of GDP, and a rerun for the base model, accounting macro model and stocks macro model will be done.

In [122]:
# creating model with accounting cleaned macro data
comp_macro_model_f1 = smf.ols("NGDP ~ qtr + atq + niq \
                            + atq_growth + niq_growth \
                            + niq_growth_lag1 + atq_growth_lag1", train_comp_macro).fit()
# printing summary of comp_macro_model_f1
print(comp_macro_model_f1.summary())

# get predicted values based off model
y_pred9 = comp_macro_model_f1.predict(test_comp_macro)
y_true9 = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred9, "8_acct_macro1_forecast")
# evaluate using RMSE:
print()
print(f"RMSE Base: {np.sqrt(mean_squared_error(y_true, y_pred))}")
print(f"RMSE w/ Accounting Macro: {np.sqrt(mean_squared_error(y_true2, y_pred2))} (Best on Kaggle)")
print(f"RMSE w/ Accounting Macro w/o Year: {np.sqrt(mean_squared_error(y_true9, y_pred9))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.391
Model:                            OLS   Adj. R-squared:                  0.331
Method:                 Least Squares   F-statistic:                     6.554
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           3.57e-07
Time:                        15:36:53   Log-Likelihood:                -220.87
No. Observations:                 102   AIC:                             461.7
Df Residuals:                      92   BIC:                             488.0
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           4.3440      0.706      6.157      0.000       2.943       5.745
qtr[T.Q2]           0.8008      0.872      0.919      0.361      -0.930       2.532
qtr[T.Q3]           0.7183      0.643      1.118      0.267      -0.558       1.994
qtr[T.Q4]           1.4372      0.873      1.647      0.103      -0.296       3.171
atq             -1.239e-07    1.9e-08     -6.509      0.000   -1.62e-07   -8.61e-08
niq              7.142e-05   1.18e-05      6.033      0.000    4.79e-05    9.49e-05
atq_growth         -0.0340      0.019     -1.790      0.077      -0.072       0.004
niq_growth          0.0002      0.000      0.858      0.393      -0.000       0.001
niq_growth_lag1    -0.0001      0.000     -0.608      0.545      -0.001       0.000
atq_growth_lag1    -0.0409      0.019     -2.135      0.035      -0.079      -0.003
==============================================================================
Omnibus:                        1.394   Durbin-Watson:                   1.771
Prob(Omnibus):                  0.498   Jarque-Bera (JB):                1.267
Skew:                          -0.271   Prob(JB):                        0.531
Kurtosis:                       2.930   Cond. No.                     1.42e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.42e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE Base: 2.96495609125275
RMSE w/ Accounting Macro: 4.200668811019781 (Best on Kaggle)
RMSE w/ Accounting Macro w/o Year: 4.55159440371707

Insights:
- while it was assumed year is not a significant predictor, it performed worse without it
- RMSE does not determine performance in prediction

### How Analysts' forecast affects GDP (Survey of Professional Forecasters)