# Forecasting GDP Growth
This project tasks you with forecasting quarterly nominal GDP growth rate in the United States. The dataset contains estimated nominal gross domestic product (GDP) annual growth rate in each quarter from 1990 to 2020, released by the Bureau of Economic Analysis (BEA) of the United States Department of Commerce. The estimate is the “third” or "final" estimate of GDP issued in the third month after the relevant quarter which is based on more complete source data than were available for the "second" estimate issued in the second month and the "advance" estimate issued in the first month after the relevant quarter. You may refer to the [BEA website](https://www.bea.gov/resources/learning-center/what-to-know-gdp) for more information on the estimate of GDP in the United States. You will train models to forecast the BEA's final GDP estimate for a quarter. Specifically you are required to answer this question: Is accounting information useful for GDP forecast? You will be allowed to use any outside data to build your model.

The evaluation pages describes how submissions will be scored and how students should format their submissions. --- The evaluation metric for this competition is [RMSE](https://en.wikipedia.org/wiki/Root-mean-square_deviation). RMSE is a measure of the accuracy of your predictions.

**Files**
- GDP_Forecast_train.csv - the training set
- GDP_Forecast_test.csv - the test set
- GDP_Forecast_sampleSubmission.csv - a sample submission file in the correct format

**Columns**
- YQ - The year and quarter variable. 1990Q1 refers to the first calendar quarter of 1990, ie, Jan - March 1990
- NGDP - nominal GDP growth rate in the quarter of the year. It is obtained from the BEA final estimate which is available at the BEA website.

**Features** (no features data provided)

Following Datar et al. (2020), you may consider the following data as your predictors/features:
- Accounting data - through COMPUSTAT on WRDS
- Stock price/return data - through CRSP on WRDS
- Analysts' forecast of GDP - through Survey of Professional Forecasters
- Any other data

In [32]:
import pandas as pd
import statsmodels.formula.api as smf
import numpy as np
from sklearn.metrics import mean_squared_error

train = pd.read_csv("data/GDP_Forecast_train.csv")
test = pd.read_csv("data/GDP_Forecast_test.csv")

def create_submission(test_df, y_pred, filename):
    df = pd.DataFrame({"YQ": test_df["YQ"], "NGDP": y_pred})
    df.to_csv(f"attempts/{filename}.csv", index = False)

## splitting year-quarter to check for traits in yearly patterns vs quarterly pattern
# ensure year is an integer
train["year"] = train["YQ"].str[:4].astype(int)
test["year"] = test["YQ"].str[:4].astype(int)
# keep qtr as string / category
train["qtr"] = train["YQ"].str[4:]
test["qtr"] = test["YQ"].str[4:]
train.head()

       YQ  NGDP  year qtr
0  1990Q1   9.0  1990  Q1
1  1990Q2   6.1  1990  Q2
2  1990Q3   3.7  1990  Q3
3  1990Q4  -0.7  1990  Q4
4  1991Q1   2.0  1991  Q1

### Base Model

In [34]:
# running base linear model
base_model = smf.ols("NGDP ~ year + qtr", train).fit()
# printing summary of base_model
print(base_model.summary())

# get predicted values based off model
y_pred = base_model.predict(test)
y_true = test["NGDP"]
create_submission(test, y_pred, "0_base_forecast")
# evaluate using RMSE:
print(f"\nRMSE: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.118
Model:                            OLS   Adj. R-squared:                  0.083
Method:                 Least Squares   F-statistic:                     3.324
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0134
Time:                        01:42:22   Log-Likelihood:                -244.91
No. Observations:                 104   AIC:                             499.8
Df Residuals:                      99   BIC:                             513.0
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    219.8404     68.424      3.213      0.002      84.073     355.608
qtr[T.Q2]      1.3038      0.725      1.799      0.075      -0.134       2.742
qtr[T.Q3]      0.5692      0.725      0.785      0.434      -0.869       2.007
qtr[T.Q4]      0.4423      0.725      0.610      0.543      -0.996       1.881
year          -0.1078      0.034     -3.154      0.002      -0.176      -0.040
==============================================================================
Omnibus:                       34.201   Durbin-Watson:                   1.137
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               83.130
Skew:                          -1.210   Prob(JB):                     8.88e-19
Kurtosis:                       6.651   Cond. No.                     5.35e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.35e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE: 2.96495609125275

### How Accounting Data affects GDP (COMPUSTAT on WRDS)
- [Compustat North America](https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/north-america-daily/) is a database of U.S. and Canadian fundamental and market information on active and inactive publicly held companies. It provides more than 300 annual and 100 quarterly Income Statement, Balance Sheet, Statement of Cash Flows, and supplemental data items. For most companies, annual history is available back to 1950 and quarterly history back to 1962 with monthly market history back to 1962.
- To consider [Execucomp](https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/execucomp/): Executive compensation data collected directly from each company’s annual proxy (DEF14A SEC form)

In [35]:
# Using Compustat North America: Fundamentals Quarterly
# https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/north-america-daily/fundamentals-quarterly/
# NOTE: currency in USD, data in STD format

compustat = pd.read_csv("data/compustat_quarterly_financials.csv")
## dropping columns with no unique data
compustat.drop(columns = ["curcdq", "datafmt", "indfmt", "consol"], inplace = True)
## dropping columns without too many missing data
# # print(compustat[compustat["ltq"].notna()].shape) # 26666 out of 85349
# compustat.drop(columns = ["ltq"], inplace = True)
## droping costat - only 2 options
compustat.drop(columns = ["costat"], inplace = True)
compustat.head()

,gvkey,datadate,conm,datacqtr,atq,ltq,niq
0,1178,1990-03-31,AFFILIATED BANKSHARES COLO,1990Q1,2597.647,NaN,2.445
1,1178,1990-06-30,AFFILIATED BANKSHARES COLO,1990Q2,2645.271,NaN,3.234
2,1178,1990-09-30,AFFILIATED BANKSHARES COLO,1990Q3,2682.906,NaN,3.253
3,1178,1990-12-31,AFFILIATED BANKSHARES COLO,1990Q4,2738.097,NaN,0.897
4,1178,1991-03-31,AFFILIATED BANKSHARES COLO,1991Q1,2655.894,NaN,3.536

- (gvkey) Global Company Key
- (conm) Company Name
- (datacqtr) Calendar Data Year and Quarter
- (atq) Assets - Total
- (ltq) Liabilities - Total
- (niq) Net Income (Loss)

In [36]:
# merge compustat data to train and test
train_comp_macro = train.merge(compustat, how = "left", left_on = "YQ", right_on = "datacqtr")
test_comp_macro = test.merge(compustat, how = "left", left_on = "YQ", right_on = "datacqtr")
train_comp_macro.head()

,YQ,NGDP,year,qtr,gvkey,datadate,conm,datacqtr,atq,ltq,niq
0,1990Q1,9.0,1990,Q1,1178,1990-03-31,AFFILIATED BANKSHARES COLO,1990Q1,2597.647,NaN,2.445
1,1990Q1,9.0,1990,Q1,1194,1990-03-31,AHMANSON (H F) & CO,1990Q1,45984.500,NaN,65.978
2,1990Q1,9.0,1990,Q1,1416,1990-03-31,AMERICAN CAPITAL CORP,1990Q1,5257.766,NaN,NaN
3,1990Q1,9.0,1990,Q1,1553,1990-03-31,AMERICAN SVGS/FL FSB,1990Q1,NaN,NaN,0.698
4,1990Q1,9.0,1990,Q1,3431,1990-03-31,CONSTELLATION BANCORP,1990Q1,NaN,NaN,NaN

In [37]:
# create base compustat model
base_comp_model = smf.ols("NGDP ~ year + qtr + conm + atq + ltq + niq", train_comp_macro).fit()
print(base_comp_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.194
Model:                            OLS   Adj. R-squared:                  0.153
Method:                 Least Squares   F-statistic:                     4.677
Date:                Wed, 04 Mar 2026   Prob (F-statistic):               0.00
Time:                        01:42:49   Log-Likelihood:                -65856.
No. Observations:               26636   AIC:                         1.343e+05
Df Residuals:                   25329   BIC:                         1.450e+05
Df Model:                        1306
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                              -94.3473     11.910     -7.922      0.000    -117.692     -71.003
qtr[T.Q2]                                1.6951      0.052     32.685      0.000       1.593       1.797
qtr[T.Q3]                                1.2468      0.052     23.979      0.000       1.145       1.349
qtr[T.Q4]                                0.4588      0.052      8.842      0.000       0.357       0.560
conm[T.1ST BERGEN BANCORP]            6.171e-08    7.5e-09      8.228      0.000     4.7e-08    7.64e-08
conm[T.1ST CAP BANCORP]                 -0.1934      0.736     -0.263      0.793      -1.637       1.250
conm[T.1ST CENTENNIAL BANCORP]          -2.0925      1.697     -1.233      0.218      -5.419       1.233
conm[T.1ST CENTURY BANCSHARES INC]      -0.8586      0.506     -1.698      0.089      -1.849       0.132
conm[T.1ST CONSTITUTION BANCORP]        -0.8867      0.521     -1.702      0.089      -1.908       0.135
conm[T.1ST ENTERPRISE BANK]              0.1987      0.736      0.270      0.787      -1.244       1.641
conm[T.1ST INDEPENDENCE FINL GROUP]     -0.1094      2.939     -0.037      0.970      -5.870       5.651
conm[T.1ST PACIFIC BANCORP]             -4.9940      1.200     -4.161      0.000      -7.346      -2.642
conm[T.1ST SOURCE CORP]                 -0.8820      0.521     -1.693      0.090      -1.903       0.139
conm[T.1ST STATE BANCORP INC]            3.1244      0.930      3.360      0.001       1.301       4.947
conm[T.1ST UNITED BANCORP INC]          -0.9947      0.567     -1.755      0.079      -2.106       0.116
conm[T.1ST UTD BANCORP]                3.72e-08   8.53e-09      4.362      0.000    2.05e-08    5.39e-08
conm[T.1ST WASHINGTON BANCORP INC]    1.128e-08   2.83e-09      3.991      0.000    5.74e-09    1.68e-08
conm[T.ABBEY NATL TREASURY SVCS PLC]     0.0045      1.471      0.003      0.998      -2.879       2.888
conm[T.ABIGAIL ADAMS NATL BANCORP]      -5.5526      1.315     -4.224      0.000      -8.129      -2.976
conm[T.ABINGTON BANCORP INC]            -1.9723      0.816     -2.418      0.016      -3.571      -0.373
conm[T.ABINGTON BANCORP INC-OLD]         3.5280      1.697      2.079      0.038       0.202       6.854
conm[T.ABN-AMRO HOLDINGS NV]             3.4490      1.130      3.053      0.002       1.235       5.663
conm[T.ABSA GROUP LTD]                  -0.8615      0.736     -1.170      0.242      -2.304       0.581
conm[T.ACADIANA BANCSHARES INC/LA]       3.3222      2.939      1.130      0.258      -2.439       9.084
conm[T.ACCESS ANYTIME BANCORP INC]       3.1244      0.930      3.360      0.001       1.302       4.947
conm[T.ACCESS NATIONAL CORP]            -0.8985      0.513     -1.751      0.080      -1.904       0.107
conm[T.ACNB CORP]                       -0.9990      0.521     -1.917      0.055      -2.020       0.022
conm[T.ADIRONDACK TRUST CO]             -0.0752      1.201     -0.063      0.950      -2.429       2.279
conm[T.ADMIRALTY BANCORP INC]        -1.706e-09   9.46e-10     -1.804      0.071   -3.56e-09    1.48e-10
conm[T.ADVANCE FINANCIAL BANCORP]        2.9959      1.200      2.496      0.013       0.643       5.349
conm[T.ADVANTAGE BANCORP]            -8.464e-11   1.38e-10     -0.612      0.540   -3.56e-10    1.86e-10
conm[T.AFFILIATED BANKSHARES COLO]   -5.231e-10   2.73e-10     -1.917      0.055   -1.06e-09    1.18e-11
conm[T.AFFILIATED COMMUNITY BANCORP]  8.355e-10   1.09e-09      0.764      0.445   -1.31e-09    2.98e-09
conm[T.AFFINITY BANCSHARES INC]         -1.9008      2.939     -0.647      0.518      -7.662       3.860
conm[T.AFSALA BANCORP INC]           -1.992e-09   1.25e-09     -1.590      0.112   -4.45e-09    4.64e-10
conm[T.AHMANSON (H F) & CO]          -2.229e-09   1.66e-09     -1.342      0.180   -5.49e-09    1.03e-09
conm[T.AIB GROUP PLC]                    0.4487      0.791      0.567      0.571      -1.102       2.000
conm[T.AJS BANCORP INC]                 -0.4480      0.850     -0.527      0.598      -2.114       1.218
conm[T.ALABAMA NATL BANCORPORATION]      2.4903      0.694      3.591      0.000       1.131       3.850
conm[T.ALAMOGORDO FINANCIAL CORP]        3.2896      1.470      2.238      0.025       0.409       6.171
conm[T.ALASKA PACIFIC BANCSHARS INC]    -1.0805      0.614     -1.760      0.078      -2.284       0.123
conm[T.ALBANK FINANCIAL CORP]         -2.38e-09   1.48e-09     -1.608      0.108   -5.28e-09     5.2e-10
conm[T.ALBEMARLE FIRST BANK]             3.0648      0.887      3.456      0.001       1.327       4.803
conm[T.ALBINA COMMUNITY BANCORP]        -1.1691      0.658     -1.776      0.076      -2.459       0.121
conm[T.ALBION BANC CORP]              1.746e-09   9.41e-10      1.855      0.064   -9.85e-11    3.59e-09
conm[T.ALERUS FINANCIAL CORP]           -0.5001      0.466     -1.073      0.283      -1.414       0.414
conm[T.ALLEGHENY BANCSHARES INC]        -1.6040      0.759     -2.112      0.035      -3.093      -0.115
conm[T.ALLEGHENY VALLEY BANCORP INC]    -0.5009      0.466     -1.074      0.283      -1.415       0.413
conm[T.ALLEGIANCE BANCORP INC]        9.341e-10    8.6e-10      1.086      0.277   -7.51e-10    2.62e-09
conm[T.ALLEGIANT BANCORP INC]            3.5298      1.697      2.080      0.038       0.203       6.856
conm[T.ALLFIRST FINANCIAL INC]       -1.905e-09   1.19e-09     -1.597      0.110   -4.24e-09    4.33e-10
conm[T.ALLIANCE BANCORP INC]             2.8190      2.940      0.959      0.338      -2.943       8.581
conm[T.ALLIANCE BANCORP NEW ENGLAND]     3.5272      1.697      2.078      0.038       0.201       6.854
conm[T.ALLIANCE BANCORP OF PA]          -0.8993      0.538     -1.672      0.095      -1.954       0.155
conm[T.ALLIANCE BANKSHARES CORP]        -1.4298      0.694     -2.062      0.039      -2.789      -0.070
conm[T.ALLIANCE FINANCIAL CORP/NY]      -1.4047      0.675     -2.081      0.037      -2.728      -0.081
conm[T.ALLIED BANK CAPITAL INC]      -1.882e-09   1.01e-09     -1.861      0.063   -3.87e-09       1e-10
conm[T.ALLIED BANKSHARES INC/GA]      1.139e-09   7.46e-10      1.527      0.127   -3.23e-10     2.6e-09
conm[T.ALTABANCORP]                     -0.7483      1.201     -0.623      0.533      -3.102       1.606
conm[T.AMB FINANCIAL CORP]              -0.8754      0.521     -1.680      0.093      -1.897       0.146
conm[T.AMBANC CORP]                  -1.091e-09    6.6e-10     -1.653      0.098   -2.38e-09    2.03e-10
conm[T.AMBANC HOLDING CO INC]        -2.714e-09   1.71e-09     -1.586      0.113   -6.07e-09    6.39e-10
conm[T.AMCORE FINANCIAL INC]            -3.9220      1.111     -3.530      0.000      -6.100      -1.744
conm[T.AMEGY BANCORPORATION INC]         3.1329      0.930      3.369      0.001       1.310       4.956
conm[T.AMERIANA BANCORP]                -0.8620      0.538     -1.602      0.109      -1.917       0.193
conm[T.AMERIBANC INVESTORS GROUP]     1.154e-09   8.11e-10      1.423      0.155   -4.36e-10    2.74e-09
conm[T.AMERICAN BANCORP NJ INC]         -4.9640      1.315     -3.776      0.000      -7.541      -2.387
conm[T.AMERICAN BANCORP/NV]          -1.598e-09   8.76e-10     -1.825      0.068   -3.31e-09    1.18e-10
conm[T.AMERICAN BANCORP/OH]           1.631e-09   9.36e-10      1.743      0.081   -2.04e-10    3.47e-09
conm[T.AMERICAN BANCSHARES INC/FL]   -1.884e-09   1.34e-09     -1.410      0.159    -4.5e-09    7.35e-10
conm[T.AMERICAN BANK CT WATERBURY]   -1.937e-10   1.75e-10     -1.106      0.269   -5.37e-10     1.5e-10
conm[T.AMERICAN BANK INC/PA]            -0.9165      0.578     -1.587      0.113      -2.049       0.216
conm[T.AMERICAN BUSINESS BANK/CA]       -0.1920      0.736     -0.261      0.794      -1.635       1.251
conm[T.AMERICAN CAPITAL CORP]         2.153e-09   1.28e-09      1.687      0.092   -3.49e-10    4.66e-09
conm[T.AMERICAN CMNTY BANCSHARES]       -4.7141      1.697     -2.778      0.005      -8.040      -1.388
conm[T.AMERICAN FINANCIAL HLDGS INC]  5.374e-10   5.97e-10      0.900      0.368   -6.33e-10    1.71e-09
conm[T.AMERICAN FSB GREENVILLE SC]    8.568e-10   1.09e-09      0.784      0.433   -1.28e-09       3e-09
conm[T.AMERICAN NATIONAL BANCORP]     7.757e-10   4.13e-10      1.876      0.061   -3.47e-11    1.59e-09
conm[T.AMERICAN NATL BANKSHARES]        -0.9991      0.521     -1.917      0.055      -2.020       0.022
conm[T.AMERICAN PACIFIC BANK  -CL B]     2.3212      1.040      2.233      0.026       0.283       4.359
conm[T.AMERICAN RIVER BANKSHARES]       -0.8795      0.521     -1.688      0.091      -1.901       0.142
conm[T.AMERICAN RIVIERA BANCORP]        -0.8151      1.470     -0.554      0.579      -3.697       2.067
conm[T.AMERICAN SAVINGS BANK-NY]     -1.791e-09   9.49e-10     -1.888      0.059   -3.65e-09    6.88e-11
conm[T.AMERICAN SVGS/FL FSB]           5.54e-10   3.47e-10      1.596      0.110   -1.26e-10    1.23e-09
conm[T.AMERICANWEST BANCORP]            -2.5676      0.930     -2.761      0.006      -4.390      -0.745
conm[T.AMERICASBANK CORP]               -3.0148      2.939     -1.026      0.305      -8.775       2.746
conm[T.AMERIFED FINANCIAL CORP]      -1.211e-09   6.92e-10     -1.750      0.080   -2.57e-09    1.46e-10
conm[T.AMERIS BANCORP]                  -0.9299      0.529     -1.757      0.079      -1.968       0.108
conm[T.AMERISERV FINANCIAL INC/PA]      -0.9337      0.529     -1.764      0.078      -1.971       0.104
conm[T.AMERITRUST CORP-OLD]            5.72e-10   1.04e-09      0.552      0.581   -1.46e-09     2.6e-09
conm[T.AMERN NATL SVGS BK FSB/MD]    -1.526e-09   2.39e-09     -0.638      0.523   -6.22e-09    3.16e-09
conm[T.AMES NATIONAL CORP]              -0.9992      0.521     -1.918      0.055      -2.020       0.022
conm[T.AMFED FINANCIAL INC]          -7.311e-10    1.2e-09     -0.610      0.542   -3.08e-09    1.62e-09
conm[T.AMITY BANCSHARES INC]         -1.536e-09      8e-10     -1.922      0.055    -3.1e-09    3.07e-11
conm[T.AMSOUTH BANCORPORATION]           3.0847      0.760      4.060      0.000       1.596       4.574
conm[T.AMTRUST CAPITAL CORP]          7.927e-11   2.88e-10      0.275      0.783   -4.85e-10    6.44e-10
conm[T.ANB CORP]                     -6.997e-10   1.34e-09     -0.523      0.601   -3.32e-09    1.92e-09
conm[T.ANCHOR BANCORP INC/NY]        -1.021e-09    5.4e-10     -1.889      0.059   -2.08e-09    3.83e-11
conm[T.ANCHOR BANCORP WISCONSIN INC]    -0.9851      0.538     -1.831      0.067      -2.040       0.069
conm[T.ANCHOR BANCORP/WA]               -0.3132      0.601     -0.521      0.603      -1.492       0.866
conm[T.ANCHOR FINANCIAL CORP/SC]      2.118e-10   1.11e-09      0.192      0.848   -1.96e-09    2.38e-09
conm[T.ANDOVER BANCORP INC/DE]       -2.373e-09   1.45e-09     -1.638      0.101   -5.21e-09    4.67e-10
conm[T.ANNAPOLIS BANCORP INC]           -1.4865      0.658     -2.259      0.024      -2.776      -0.197
conm[T.ANNAPOLIS BANCSHARES INC]     -7.768e-10    6.3e-10     -1.232      0.218   -2.01e-09    4.59e-10
conm[T.ANZ GROUP HOLDINGS LIMITED]       0.2675      0.670      0.399      0.690      -1.046       1.581
conm[T.APPALACHIAN BANCSHARES INC]      -5.1268      1.200     -4.272      0.000      -7.479      -2.775
conm[T.APPLE BANCORP INC]             1.002e-09   5.64e-10      1.777      0.076   -1.03e-10    2.11e-09
conm[T.AREA BANCSHARES CORP]         -1.218e-09      1e-09     -1.217      0.224   -3.18e-09    7.44e-10
conm[T.ARGENT BANK/LA]               -1.664e-09   1.06e-09     -1.571      0.116   -3.74e-09    4.12e-10
conm[T.ARGENTARIA CAJA POST BANC HP]   1.73e-09   1.54e-09      1.123      0.261   -1.29e-09    4.75e-09
conm[T.ARIZONA COMMERCE BANK]         -1.38e-09   7.29e-10     -1.893      0.058   -2.81e-09    4.92e-11
conm[T.ARROW FINANCIAL CORP]            -0.9979      0.521     -1.915      0.055      -2.019       0.023
conm[T.ASB BANCORP INC]                 -0.0369      0.628     -0.059      0.953      -1.268       1.194
conm[T.ASB FINANCIAL CORP]            5.574e-09    3.3e-09      1.689      0.091   -8.94e-10     1.2e-08
conm[T.ASB HAWAII INC -SPN]              0.4173      2.079      0.201      0.841      -3.657       4.492
conm[T.ASPEN BANCSHARES INC]         -3.865e-09    2.3e-09     -1.682      0.093   -8.37e-09    6.38e-10
conm[T.ASSOCIATED BANC-CORP]            -0.8970      0.529     -1.695      0.090      -1.934       0.140
conm[T.ASTORIA FINANCIAL CORP]          -0.9039      0.529     -1.708      0.088      -1.941       0.134
conm[T.ATHENS BANCSHARES CORP]          -0.6185      0.557     -1.111      0.267      -1.710       0.473
conm[T.ATLANFED BANCORP INC]          1.018e-10   9.52e-10      0.107      0.915   -1.76e-09    1.97e-09
conm[T.ATLANTIC BANCGROUP INC]          -2.9028      0.930     -3.122      0.002      -4.725      -1.080
conm[T.ATLANTIC CAP BANCSHARES INC]     -0.8855      1.315     -0.673      0.501      -3.464       1.693
conm[T.ATLANTIC CMNTY BANCORP INC]   -9.826e-10   9.45e-10     -1.039      0.299   -2.84e-09    8.71e-10
conm[T.ATLANTIC COAST FINANCIAL CP]     -0.9332      0.529     -1.763      0.078      -1.971       0.104
conm[T.ATLANTIC FINANCIAL CORP]       2.159e-09   1.19e-09      1.813      0.070   -1.75e-10    4.49e-09
conm[T.ATLANTIC LIBERTY FINANCIAL]       3.2912      0.849      3.876      0.000       1.627       4.955
conm[T.ATLANTIC SOUTHERN FINL GRP]      -2.5741      0.930     -2.768      0.006      -4.397      -0.752
conm[T.ATLANTIC UNION BANKSHRS CRP]     -0.9289      0.529     -1.755      0.079      -1.967       0.109
conm[T.AUBURN BANCORP INC]              -1.2267      0.601     -2.040      0.041      -2.405      -0.048
conm[T.AUBURN NATIONAL BANCORP]         -0.9993      0.521     -1.918      0.055      -2.021       0.022
conm[T.AVENUE FINANCIAL HOLDINGS]       -0.4006      1.040     -0.385      0.700      -2.440       1.638
conm[T.AVIDBANK HOLDINGS INC]           -0.2167      0.659     -0.329      0.742      -1.508       1.074
conm[T.AXOS FINANCIAL INC]              -0.9324      0.529     -1.761      0.078      -1.970       0.105
conm[T.B M J FINANCIAL CORP]          6.864e-10   4.85e-10      1.417      0.157   -2.63e-10    1.64e-09
conm[T.BAKER BOYER BANCORP]              0.2424      1.112      0.218      0.827      -1.937       2.422
conm[T.BALTIMORE BANCORP]            -5.632e-10   1.19e-09     -0.474      0.636   -2.89e-09    1.77e-09
conm[T.BANC OF CALIFORNIA INC]          -0.9214      0.529     -1.741      0.082      -1.959       0.116
conm[T.BANC OF CALIFORNIA INC -OLD]     -0.9313      0.529     -1.759      0.079      -1.969       0.106
conm[T.BANCFIRST CORP/OK]               -0.9280      0.529     -1.753      0.080      -1.966       0.110
conm[T.BANCFLORIDA FINANCIAL CORP]   -3.834e-10   6.29e-10     -0.610      0.542   -1.62e-09    8.49e-10
conm[T.BANCO BBVA ARGENTINA SA]         -1.0011      0.521     -1.921      0.055      -2.022       0.020
conm[T.BANCO BILBAO VIZCAYA ARGENTA]     0.6854      0.493      1.391      0.164      -0.280       1.651
conm[T.BANCO CENTRAL HISPANO]        -2.033e-09   1.08e-09     -1.887      0.059   -4.15e-09    7.91e-11
conm[T.BANCO COMERCIAL PORTUGUES SA]     2.7355      1.697      1.612      0.107      -0.591       6.062
conm[T.BANCO DE A EDWARDS SA]           2.8e-09   1.57e-09      1.780      0.075   -2.82e-10    5.88e-09
conm[T.BANCO DE CHILE]                  -0.6425      0.485     -1.326      0.185      -1.592       0.307
conm[T.BANCO GALICIA BUENOS AIRES]       2.9775      1.471      2.024      0.043       0.094       5.861
conm[T.BANCO ITAU CHILE]                -0.0156      0.435     -0.036      0.971      -0.868       0.836
conm[T.BANCO LATINOAMERICANO DE COM]     1.0351      0.325      3.190      0.001       0.399       1.671
conm[T.BANCO MACRO SA]                  -0.7607      0.491     -1.548      0.122      -1.724       0.202
conm[T.BANCO SANTANDER ARGENTINA]        1.6871      2.078      0.812      0.417      -2.387       5.761
conm[T.BANCO SANTANDER BRASIL  -ADR]    -0.4030      0.564     -0.714      0.475      -1.509       0.703
conm[T.BANCO SANTANDER CHILE SA]     -1.591e-09   1.11e-09     -1.429      0.153   -3.77e-09    5.91e-10
conm[T.BANCO SANTANDER MEXICO -ADR]     -0.3061      0.787     -0.389      0.697      -1.848       1.236
conm[T.BANCO SANTANDER SA]               2.1665      0.529      4.099      0.000       1.131       3.202
conm[T.BANCO SANTANDER-CHILE]           -0.7937      0.478     -1.660      0.097      -1.731       0.143
conm[T.BANCOKLAHOMA CORP]            -6.193e-10    4.1e-10     -1.512      0.130   -1.42e-09    1.83e-10
conm[T.BANCORP CONN INC]                 2.0587      2.939      0.700      0.484      -3.703       7.820
conm[T.BANCORP INC]                     -0.9292      0.529     -1.755      0.079      -1.967       0.108
conm[T.BANCORP NEW JERSEY INC]        8.567e-10   4.44e-10      1.929      0.054   -1.36e-11    1.73e-09
conm[T.BANCORP OF NEW JERSEY INC]       -0.9347      0.529     -1.766      0.077      -1.972       0.103
conm[T.BANCORP RHODE ISLAND INC]        -1.9670      0.786     -2.502      0.012      -3.508      -0.426
conm[T.BANCTRUST FINANCIAL GRP INC]     -1.5079      0.675     -2.234      0.026      -2.831      -0.185
conm[T.BANCWEST CORP]                 1.276e-10   5.78e-10      0.221      0.825      -1e-09    1.26e-09
conm[T.BANK FIRST CORP]                 -0.1928      0.736     -0.262      0.793      -1.636       1.250
conm[T.BANK HOLDINGS INC]               -3.9388      1.111     -3.545      0.000      -6.117      -1.761
conm[T.BANK KY FINANCIAL CORP]          -0.9202      0.547     -1.682      0.093      -1.993       0.152
conm[T.BANK LOS ANGELES/CA]           1.316e-09   6.94e-10      1.898      0.058   -4.31e-11    2.68e-09
conm[T.BANK MARYLAND CORP]            1.921e-09   1.22e-09      1.571      0.116   -4.75e-10    4.32e-09
conm[T.BANK MUTUAL CORP]                -0.9297      0.529     -1.756      0.079      -1.967       0.108
conm[T.BANK NEW HAMPSHIRE CORP]      -1.842e-10   3.42e-10     -0.538      0.590   -8.55e-10    4.87e-10
conm[T.BANK OF AMERICA CORP]             2.8318      0.383      7.403      0.000       2.082       3.582
conm[T.BANK OF BERMUDA LTD]              3.5447      1.697      2.089      0.037       0.218       6.871
conm[T.BANK OF COMMERCE HOLDINGS]       -0.9341      0.529     -1.764      0.078      -1.972       0.104
conm[T.BANK OF COMMERCE SAN DIEGO]   -2.145e-09   1.11e-09     -1.925      0.054   -4.33e-09    3.93e-11
conm[T.BANK OF FLORIDA CORP]            -2.5704      0.930     -2.764      0.006      -4.393      -0.748
conm[T.BANK OF GRANITE CORP]            -1.8435      0.759     -2.427      0.015      -3.332      -0.355
conm[T.BANK OF HAWAII CORP]              1.2104      0.291      4.154      0.000       0.639       1.781
conm[T.BANK OF IRELAND GROUP PLC]        0.3147      0.629      0.501      0.617      -0.918       1.547
conm[T.BANK OF MARIN BANCORP]           -0.9337      0.529     -1.764      0.078      -1.971       0.104

Insights: too many companies, run time too long, with all the companies, Assets is highly insignificant (p-value: 0.983)

In [ ]:
## create aggregates for assets, liabilities and net income
compustat_macro = compustat.groupby("datacqtr").agg({"atq": "sum", "ltq": "sum", "niq": "sum"}).reset_index()
compustat_macro.sort_values(by = "datacqtr")

# calculate lag
compustat_macro["atq_lag"] = compustat_macro["atq"].shift(1)
compustat_macro["ltq_lag"] = compustat_macro["ltq"].shift(1)
compustat_macro["niq_lag"] = compustat_macro["niq"].shift(1)
# calculate growth
compustat_macro["atq_growth"] = compustat_macro["atq"] / compustat_macro["atq_lag"] - 1
compustat_macro["ltq_growth"] = compustat_macro["ltq"] / compustat_macro["ltq_lag"] - 1
compustat_macro["niq_growth"] = compustat_macro["niq"] / compustat_macro["niq_lag"] - 1
# converting infinite values to NaN
compustat_macro = compustat_macro.replace([np.inf, -np.inf], np.nan)
compustat_macro.head()

,datacqtr,atq,ltq,niq,atq_lag,ltq_lag,niq_lag,atq_growth,ltq_growth,niq_growth
0,1989Q4,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN
1,1990Q1,3187273.043,224746.034,4684.085,0.000,0.000,0.000,NaN,NaN,NaN
2,1990Q2,3412321.689,236377.703,6396.105,3187273.043,224746.034,4684.085,0.070609,0.051755,0.365497
3,1990Q3,3473969.743,239062.003,3093.203,3412321.689,236377.703,6396.105,0.018066,0.011356,-0.516393
4,1990Q4,3426461.019,245699.448,-49.699,3473969.743,239062.003,3093.203,-0.013676,0.027765,-1.016067

In [39]:
# merge compustat data to train and test
train_comp_macro = train.merge(compustat_macro, how = "left", left_on = "YQ", right_on = "datacqtr")
test_comp_macro = test.merge(compustat_macro, how = "left", left_on = "YQ", right_on = "datacqtr")
train_comp_macro.head()

,YQ,NGDP,year,qtr,datacqtr,atq,ltq,niq,atq_lag,ltq_lag,niq_lag,atq_growth,ltq_growth,niq_growth
0,1990Q1,9.0,1990,Q1,1990Q1,3187273.043,224746.034,4684.085,0.000,0.000,0.000,NaN,NaN,NaN
1,1990Q2,6.1,1990,Q2,1990Q2,3412321.689,236377.703,6396.105,3187273.043,224746.034,4684.085,0.070609,0.051755,0.365497
2,1990Q3,3.7,1990,Q3,1990Q3,3473969.743,239062.003,3093.203,3412321.689,236377.703,6396.105,0.018066,0.011356,-0.516393
3,1990Q4,-0.7,1990,Q4,1990Q4,3426461.019,245699.448,-49.699,3473969.743,239062.003,3093.203,-0.013676,0.027765,-1.016067
4,1991Q1,2.0,1991,Q1,1991Q1,3330827.317,296801.210,4647.742,3426461.019,245699.448,-49.699,-0.027910,0.207985,-94.517817

In [40]:
comp_model_atq = smf.ols("NGDP ~ year + qtr + atq", train_comp_macro).fit()
print(comp_model_atq.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.139
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     3.154
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0111
Time:                        01:42:50   Log-Likelihood:                -243.71
No. Observations:                 104   AIC:                             499.4
Df Residuals:                      98   BIC:                             515.3
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -101.0021    222.389     -0.454      0.651    -542.325     340.321
qtr[T.Q2]      1.6200      0.750      2.161      0.033       0.132       3.108
qtr[T.Q3]      0.6221      0.721      0.863      0.390      -0.809       2.053
qtr[T.Q4]      0.8402      0.766      1.096      0.276      -0.681       2.361
year           0.0532      0.112      0.477      0.634      -0.168       0.275
atq        -9.098e-08      6e-08     -1.515      0.133    -2.1e-07    2.82e-08
==============================================================================
Omnibus:                       31.022   Durbin-Watson:                   1.188
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               65.910
Skew:                          -1.153   Prob(JB):                     4.87e-15
Kurtosis:                       6.145   Cond. No.                     2.03e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.03e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [42]:
comp_model_atq_lag = smf.ols("NGDP ~ year + qtr + atq_lag", train_comp_macro).fit()
print(comp_model_atq_lag.summary())

y_pred = comp_model_atq_lag.predict(test_comp_macro)
y_true = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred, "1_compustat_atqlag_forecast")
# evaluate using RMSE:
print(f"\nRMSE w Assets Lag Macro: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.151
Model:                            OLS   Adj. R-squared:                  0.107
Method:                 Least Squares   F-statistic:                     3.477
Date:                Wed, 04 Mar 2026   Prob (F-statistic):            0.00618
Time:                        01:43:45   Log-Likelihood:                -242.98
No. Observations:                 104   AIC:                             498.0
Df Residuals:                      98   BIC:                             513.8
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -187.9737    221.947     -0.847      0.399    -628.421     252.473
qtr[T.Q2]      0.9689      0.736      1.317      0.191      -0.491       2.429
qtr[T.Q3]      0.6354      0.716      0.888      0.377      -0.785       2.056
qtr[T.Q4]      0.1745      0.728      0.240      0.811      -1.271       1.620
year           0.0970      0.111      0.871      0.386      -0.124       0.318
atq_lag    -1.155e-07   5.99e-08     -1.929      0.057   -2.34e-07    3.33e-09
==============================================================================
Omnibus:                       38.748   Durbin-Watson:                   1.221
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              110.632
Skew:                          -1.306   Prob(JB):                     9.47e-25
Kurtosis:                       7.325   Cond. No.                     2.02e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.02e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE w Assets Lag Macro: 3.526561045682736

In [44]:
comp_model_atq_growth = smf.ols("NGDP ~ year + qtr + atq_growth", train_comp_macro).fit()
print(comp_model_atq_growth.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.114
Model:                            OLS   Adj. R-squared:                  0.069
Method:                 Least Squares   F-statistic:                     2.503
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0355
Time:                        01:43:53   Log-Likelihood:                -241.96
No. Observations:                 103   AIC:                             495.9
Df Residuals:                      97   BIC:                             511.7
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    202.9811     69.390      2.925      0.004      65.260     340.702
qtr[T.Q2]      1.4877      0.898      1.656      0.101      -0.295       3.271
qtr[T.Q3]      0.7239      0.736      0.984      0.328      -0.737       2.185
qtr[T.Q4]      0.6341      0.974      0.651      0.516      -1.299       2.567
year          -0.0994      0.035     -2.871      0.005      -0.168      -0.031
atq_growth    -0.0990      1.507     -0.066      0.948      -3.091       2.893
==============================================================================
Omnibus:                       35.139   Durbin-Watson:                   1.132
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               88.387
Skew:                          -1.238   Prob(JB):                     6.41e-20
Kurtosis:                       6.804   Cond. No.                     5.40e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.4e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [45]:
comp_model_ltq = smf.ols("NGDP ~ year + qtr + ltq", train_comp_macro).fit()
print(comp_model_ltq.summary())

y_pred = comp_model_ltq.predict(test_comp_macro)
y_true = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred, "2_compustat_ltq_forecast")
# evaluate using RMSE:
print(f"\nRMSE w Liabilities Macro: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.164
Model:                            OLS   Adj. R-squared:                  0.122
Method:                 Least Squares   F-statistic:                     3.849
Date:                Wed, 04 Mar 2026   Prob (F-statistic):            0.00316
Time:                        01:44:48   Log-Likelihood:                -242.14
No. Observations:                 104   AIC:                             496.3
Df Residuals:                      98   BIC:                             512.2
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -76.4702    144.408     -0.530      0.598    -363.043     210.102
qtr[T.Q2]      1.5016      0.714      2.102      0.038       0.084       2.919
qtr[T.Q3]      0.6251      0.710      0.881      0.381      -0.783       2.034
qtr[T.Q4]      0.6711      0.716      0.937      0.351      -0.750       2.092
year           0.0407      0.072      0.562      0.575      -0.103       0.184
ltq        -8.408e-08   3.63e-08     -2.316      0.023   -1.56e-07    -1.2e-08
==============================================================================
Omnibus:                       27.503   Durbin-Watson:                   1.240
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               52.787
Skew:                          -1.065   Prob(JB):                     3.45e-12
Kurtosis:                       5.765   Cond. No.                     1.13e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.13e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE w Liabilities Macro: 3.1749235968328033

In [47]:
comp_model_ltq_lag = smf.ols("NGDP ~ year + qtr + ltq_lag", train_comp_macro).fit()
print(comp_model_ltq_lag.summary())

y_pred = comp_model_ltq_lag.predict(test_comp_macro)
y_true = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred, "3_compustat_ltqlag_forecast")
# evaluate using RMSE:
print(f"\nRMSE w Liabilities Lag Macro: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.172
Model:                            OLS   Adj. R-squared:                  0.130
Method:                 Least Squares   F-statistic:                     4.074
Date:                Wed, 04 Mar 2026   Prob (F-statistic):            0.00211
Time:                        01:45:36   Log-Likelihood:                -241.65
No. Observations:                 104   AIC:                             495.3
Df Residuals:                      98   BIC:                             511.2
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -94.6095    141.447     -0.669      0.505    -375.307     186.088
qtr[T.Q2]      1.1807      0.708      1.668      0.098      -0.224       2.585
qtr[T.Q3]      0.6583      0.707      0.931      0.354      -0.744       2.061
qtr[T.Q4]      0.3790      0.706      0.537      0.593      -1.023       1.781
year           0.0498      0.071      0.703      0.484      -0.091       0.190
ltq_lag    -9.025e-08   3.58e-08     -2.520      0.013   -1.61e-07   -1.92e-08
==============================================================================
Omnibus:                       34.655   Durbin-Watson:                   1.221
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               87.328
Skew:                          -1.209   Prob(JB):                     1.09e-19
Kurtosis:                       6.782   Cond. No.                     1.09e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.09e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE w Liabilities Lag Macro: 3.1226396973402273

In [48]:
comp_model_ltq_growth = smf.ols("NGDP ~ year + qtr + ltq_growth", train_comp_macro).fit()
print(comp_model_ltq_growth.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.117
Model:                            OLS   Adj. R-squared:                  0.072
Method:                 Least Squares   F-statistic:                     2.577
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0311
Time:                        01:45:44   Log-Likelihood:                -241.79
No. Observations:                 103   AIC:                             495.6
Df Residuals:                      97   BIC:                             511.4
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    198.5943     69.696      2.849      0.005      60.268     336.921
qtr[T.Q2]      1.3463      0.754      1.785      0.077      -0.150       2.843
qtr[T.Q3]      0.6798      0.734      0.926      0.357      -0.777       2.136
qtr[T.Q4]      0.3784      0.819      0.462      0.645      -1.248       2.004
year          -0.0972      0.035     -2.794      0.006      -0.166      -0.028
ltq_growth     0.4026      0.698      0.576      0.566      -0.984       1.789
==============================================================================
Omnibus:                       36.079   Durbin-Watson:                   1.123
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               94.772
Skew:                          -1.253   Prob(JB):                     2.63e-21
Kurtosis:                       6.976   Cond. No.                     5.43e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.43e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [53]:
comp_model_niq = smf.ols("NGDP ~ year + qtr + niq", train_comp_macro).fit()
print(comp_model_niq.summary())

y_pred = comp_model_niq.predict(test_comp_macro)
y_true = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred, "4_compustat_niq_forecast")
# evaluate using RMSE:
print(f"\nRMSE w Net Income Macro: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.312
Method:                 Least Squares   F-statistic:                     10.33
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           5.63e-08
Time:                        01:56:46   Log-Likelihood:                -229.45
No. Observations:                 104   AIC:                             470.9
Df Residuals:                      98   BIC:                             486.8
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    485.4484     74.782      6.492      0.000     337.047     633.850
qtr[T.Q2]      0.9281      0.631      1.470      0.145      -0.324       2.181
qtr[T.Q3]      0.7116      0.628      1.132      0.260      -0.535       1.958
qtr[T.Q4]      0.9109      0.633      1.439      0.153      -0.345       2.167
year          -0.2415      0.037     -6.448      0.000      -0.316      -0.167
niq          7.18e-05   1.23e-05      5.825      0.000    4.73e-05    9.63e-05
==============================================================================
Omnibus:                        2.070   Durbin-Watson:                   1.625
Prob(Omnibus):                  0.355   Jarque-Bera (JB):                1.723
Skew:                          -0.313   Prob(JB):                        0.422
Kurtosis:                       3.072   Cond. No.                     1.28e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.28e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE w Net Income Macro: 3.3948414864271554

In [54]:
comp_model_niq_lag = smf.ols("NGDP ~ year + qtr + niq_lag", train_comp_macro).fit()
print(comp_model_niq_lag.summary())

y_pred = comp_model_niq_lag.predict(test_comp_macro)
y_true = test_comp_macro["NGDP"]
create_submission(test_comp_macro, y_pred, "5_compustat_niqlag_forecast")
# evaluate using RMSE:
print(f"\nRMSE w Net Income Lag Macro: {np.sqrt(mean_squared_error(y_true, y_pred))}")

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.301
Model:                            OLS   Adj. R-squared:                  0.265
Method:                 Least Squares   F-statistic:                     8.439
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           1.14e-06
Time:                        01:59:57   Log-Likelihood:                -232.85
No. Observations:                 104   AIC:                             477.7
Df Residuals:                      98   BIC:                             493.6
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    466.2873     78.252      5.959      0.000     310.998     621.576
qtr[T.Q2]      0.8129      0.656      1.239      0.218      -0.489       2.115
qtr[T.Q3]     -0.2611      0.669     -0.390      0.697      -1.589       1.067
qtr[T.Q4]      0.0800      0.653      0.123      0.903      -1.215       1.375
year          -0.2316      0.039     -5.913      0.000      -0.309      -0.154
niq_lag     6.487e-05   1.28e-05      5.059      0.000    3.94e-05    9.03e-05
==============================================================================
Omnibus:                       10.980   Durbin-Watson:                   1.619
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               13.272
Skew:                          -0.581   Prob(JB):                      0.00131
Kurtosis:                       4.309   Cond. No.                     1.30e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

RMSE w Net Income Lag Macro: 3.2575786220077223

In [51]:
comp_model_niq_growth = smf.ols("NGDP ~ year + qtr + niq_growth", train_comp_macro).fit()
print(comp_model_niq_growth.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.120
Model:                            OLS   Adj. R-squared:                  0.074
Method:                 Least Squares   F-statistic:                     2.640
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0278
Time:                        01:46:48   Log-Likelihood:                -241.64
No. Observations:                 103   AIC:                             495.3
Df Residuals:                      97   BIC:                             511.1
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    212.8997     70.311      3.028      0.003      73.352     352.448
qtr[T.Q2]      1.3687      0.738      1.855      0.067      -0.095       2.833
qtr[T.Q3]      0.6451      0.736      0.877      0.383      -0.815       2.105
qtr[T.Q4]      0.5053      0.738      0.685      0.495      -0.960       1.970
year          -0.1043      0.035     -2.973      0.004      -0.174      -0.035
niq_growth     0.0220      0.028      0.781      0.437      -0.034       0.078
==============================================================================
Omnibus:                       37.833   Durbin-Watson:                   1.165
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              104.112
Skew:                          -1.298   Prob(JB):                     2.47e-23
Kurtosis:                       7.186   Cond. No.                     5.49e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.49e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

|Model|RMSE|Adj R-Squared|Score|
|---|---|---|---|
|Base Model RMSE|2.96495609125275|0.083|11.58888|
|RMSE w Assets Lag Macro|3.526561045682736|0.107|11.47981|
|RMSE w Liabilities Macro|3.1749235968328033|0.122|11.63967|
|RMSE w Liabilities Lag Macro|3.122639697340227|0.130|11.52818|
|RMSE w Net Income Macro|3.3948414864271554|0.312|10.76603|
|RMSE w Net Income Lag Macro|3.2575786220077223|0.265|11.71961|

### How Stock Price / Return Data affects GDP (CRSP on WRDS)
1. Essential Variables (The "Core" Signal)
- (dlycaldt) Daily Calendar Date: daily moves into Year-Quarter (YQ) buckets
- (dlytotret) Daily Total Return on Index: This includes dividends. In forensic finance, this is the most powerful leading indicator. It represents the market's "real-time" discount of future economic growth.
- (dlytotval) Index Total Capitalization Value: This is the aggregate dollar value of all firms in the index. Use this to measure the Wealth Effect. If this value rises significantly, consumer spending (the biggest part of GDP) usually follows 1–2 quarters later.

2. Forensic Variables (To Lower Your RMSE)
- (dlytotind) Daily Index Level: Useful if you want to calculate the "momentum" of the market (e.g., comparing the current level to a 200-day moving average).
- (dlyincret) Daily Income Return on Index: This isolates the dividend component. A high income return relative to price return often signals a "flight to quality," which forensically precedes economic slowdowns.
- (dlyusdcnt) Used Count: The number of firms currently in the index. Rapid changes in the count of firms can signal structural shifts in the economy (like a wave of IPOs or bankruptcies).

In [72]:
# Using CRSP Daily Index and Portfolios on S&P 500
# https://wrds-www.wharton.upenn.edu/pages/get-data/center-research-security-prices-crsp/annual-update/index-version-2/daily-index-and-portfolios-on-sp-500/

crsp_daily_macro = pd.read_csv("data/crsp_snp500_indexes.csv")
## dropping columns with no unique data
# print(crsp_daily_macro[crsp_daily_macro["INDNO"] != 1000500].shape)
crsp_daily_macro.drop(columns = "INDNO", inplace = True)

## creating year, month and quarter identifiers
crsp_daily_macro["DlyCalDt"] = pd.to_datetime(crsp_daily_macro["DlyCalDt"])
crsp_daily_macro.set_index("DlyCalDt", inplace = True)
crsp_daily_macro.head()

            DlyTotRet  DlyTotInd  DlyIncRet  DlyUsdCnt   DlyTotVal
DlyCalDt
1990-01-02   0.017527     633.75   0.000000        500  2371902979
1990-01-03  -0.002028     632.47   0.000020        500  2367046297
1990-01-04  -0.007913     627.46   0.000434        500  2347288970
1990-01-05  -0.010069     621.14   0.000023        500  2323602293
1990-01-08   0.004798     624.12   0.000088        500  2334547314

Since we need to convert the data from daily values to quarterly values, we can use `resample()`<br>
Create a `YQ` column for easier merge, then we can drop `DlyCalDt`<br>
After creating the aggregate quarterly values, create the lag as market signals to predict current quarter

In [73]:
## create quarterly data
crsp_qtr_macro = crsp_daily_macro.resample("Q").agg({
    "DlyTotRet": [
        ("qtr_ret", lambda x: (1+x).prod() - 1),    # compounded total return
        ("qtr_vola", "std")                         # quarterly volatility
    ],
    "DlyTotInd": [("qtr_idx_level", "last")],       # final index level
    "DlyIncRet": [("qtr_income_ret", "sum")],       # total income return on index
    "DlyUsdCnt": [("avg_firm_count", "mean")]       # average number of firms
})

crsp_qtr_macro.columns = crsp_qtr_macro.columns.droplevel(0)
crsp_qtr_macro.reset_index(inplace = True)
## creating YQ column and moving it to first column
crsp_qtr_macro["YQ"] = crsp_qtr_macro["DlyCalDt"].dt.year.astype(str) + "Q" + crsp_qtr_macro["DlyCalDt"].dt.quarter.astype(str)
crsp_qtr_macro.drop(columns = "DlyCalDt", inplace = True)
col = crsp_qtr_macro.pop("YQ")
crsp_qtr_macro.insert(0, "YQ", col)
crsp_qtr_macro.sort_values(by = "YQ", inplace = True)
market_cols = "qtr_ret", "qtr_vola", "qtr_idx_level", "qtr_income_ret", "avg_firm_count"
# creating last column market signals to predict current quarter
for col in market_cols: crsp_qtr_macro[f"{col}_lag"] = crsp_qtr_macro[col].shift(1)
crsp_qtr_macro

C:\Users\sbgka\AppData\Local\Temp\ipykernel_26536\3879900254.py:2: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  crsp_qtr_macro = crsp_daily_macro.resample("Q").agg({

,YQ,qtr_ret,qtr_vola,qtr_idx_level,qtr_income_ret,avg_firm_count,qtr_ret_lag,qtr_vola_lag,qtr_idx_level_lag,qtr_income_ret_lag,avg_firm_count_lag
0,1990Q1,-0.030222,0.008859,604.01,0.008371,499.984127,NaN,NaN,NaN,NaN,NaN
1,1990Q2,0.063453,0.007631,642.34,0.008977,500.000000,-0.030222,0.008859,604.01,0.008371,499.984127
2,1990Q3,-0.139556,0.011900,552.70,0.008717,499.984127,0.063453,0.007631,642.34,0.008977,500.000000
3,1990Q4,0.090365,0.011030,602.64,0.010018,500.000000,-0.139556,0.011900,552.70,0.008717,499.984127
4,1991Q1,0.147108,0.010541,691.30,0.008023,500.000000,0.090365,0.011030,602.64,0.010018,500.000000
...,...,...,...,...,...,...,...,...,...,...,...
119,2019Q4,0.089929,0.005923,10872.55,0.005012,505.000000,0.016904,0.009357,9975.45,0.005074,504.890625
120,2020Q1,-0.194095,0.035693,8762.26,0.005267,504.967742,0.089929,0.005923,10872.55,0.005012,505.000000
121,2020Q2,0.206679,0.019921,10573.22,0.004871,505.000000,-0.194095,0.035693,8762.26,0.005267,504.967742
122,2020Q3,0.089977,0.010664,11524.56,0.004149,505.000000,0.206679,0.019921,10573.22,0.004871,505.000000
123,2020Q4,0.121923,0.010263,12929.70,0.004153,504.921875,0.089977,0.010664,11524.56,0.004149,505.000000

In [74]:
# merging updated macro to train and test sets
train_crsp_macro = train.merge(crsp_qtr_macro, on = "YQ", how = "left")
test_crsp_macro = test.merge(crsp_qtr_macro, on = "YQ", how = "left")
train_crsp_macro.head()

,YQ,NGDP,year,qtr,qtr_ret,qtr_vola,qtr_idx_level,qtr_income_ret,avg_firm_count,qtr_ret_lag,qtr_vola_lag,qtr_idx_level_lag,qtr_income_ret_lag,avg_firm_count_lag
0,1990Q1,9.0,1990,Q1,-0.030222,0.008859,604.01,0.008371,499.984127,NaN,NaN,NaN,NaN,NaN
1,1990Q2,6.1,1990,Q2,0.063453,0.007631,642.34,0.008977,500.000000,-0.030222,0.008859,604.01,0.008371,499.984127
2,1990Q3,3.7,1990,Q3,-0.139556,0.011900,552.70,0.008717,499.984127,0.063453,0.007631,642.34,0.008977,500.000000
3,1990Q4,-0.7,1990,Q4,0.090365,0.011030,602.64,0.010018,500.000000,-0.139556,0.011900,552.70,0.008717,499.984127
4,1991Q1,2.0,1991,Q1,0.147108,0.010541,691.30,0.008023,500.000000,0.090365,0.011030,602.64,0.010018,500.000000

## STOPPED HERE

In [75]:
crsp_model_ret = smf.ols("NGDP ~ year + qtr + qtr_ret", train_crsp_macro).fit()
print(crsp_model_ret.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.194
Model:                            OLS   Adj. R-squared:                  0.153
Method:                 Least Squares   F-statistic:                     4.727
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           0.000654
Time:                        02:46:29   Log-Likelihood:                -240.23
No. Observations:                 104   AIC:                             492.5
Df Residuals:                      98   BIC:                             508.3
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    207.6220     65.868      3.152      0.002      76.909     338.335
qtr[T.Q2]      1.2472      0.697      1.790      0.077      -0.135       2.630
qtr[T.Q3]      0.8009      0.701      1.143      0.256      -0.589       2.191
qtr[T.Q4]      0.1009      0.705      0.143      0.887      -1.299       1.501
year          -0.1018      0.033     -3.095      0.003      -0.167      -0.037
qtr_ret        9.8879      3.254      3.038      0.003       3.430      16.346
==============================================================================
Omnibus:                       18.621   Durbin-Watson:                   1.274
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.607
Skew:                          -0.850   Prob(JB):                     1.67e-06
Kurtosis:                       4.802   Cond. No.                     5.36e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.36e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [76]:
crsp_model_ret_lag = smf.ols("NGDP ~ year + qtr + qtr_ret_lag", train_crsp_macro).fit()
print(crsp_model_ret_lag.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.218
Model:                            OLS   Adj. R-squared:                  0.177
Method:                 Least Squares   F-statistic:                     5.400
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           0.000200
Time:                        02:46:30   Log-Likelihood:                -235.57
No. Observations:                 103   AIC:                             483.1
Df Residuals:                      97   BIC:                             498.9
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     187.4154     65.351      2.868      0.005      57.711     317.119
qtr[T.Q2]       1.8444      0.696      2.648      0.009       0.462       3.227
qtr[T.Q3]       1.0445      0.694      1.505      0.135      -0.333       2.422
qtr[T.Q4]       1.2501      0.712      1.756      0.082      -0.163       2.663
year           -0.0920      0.033     -2.820      0.006      -0.157      -0.027
qtr_ret_lag    11.4041      3.183      3.583      0.001       5.087      17.722
==============================================================================
Omnibus:                       23.009   Durbin-Watson:                   1.458
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.535
Skew:                          -0.855   Prob(JB):                     4.76e-11
Kurtosis:                       5.855   Cond. No.                     5.41e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.41e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [77]:
crsp_model_vola = smf.ols("NGDP ~ year + qtr + qtr_vola", train_crsp_macro).fit()
print(crsp_model_vola.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.391
Model:                            OLS   Adj. R-squared:                  0.360
Method:                 Least Squares   F-statistic:                     12.60
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           1.87e-09
Time:                        02:46:30   Log-Likelihood:                -225.65
No. Observations:                 104   AIC:                             463.3
Df Residuals:                      98   BIC:                             479.2
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    157.8598     57.905      2.726      0.008      42.949     272.771
qtr[T.Q2]      1.1911      0.606      1.967      0.052      -0.011       2.393
qtr[T.Q3]      0.7393      0.606      1.220      0.225      -0.463       1.942
qtr[T.Q4]      0.6792      0.606      1.120      0.265      -0.524       1.883
year          -0.0755      0.029     -2.608      0.011      -0.133      -0.018
qtr_vola    -271.4325     40.950     -6.628      0.000    -352.697    -190.168
==============================================================================
Omnibus:                        0.957   Durbin-Watson:                   1.427
Prob(Omnibus):                  0.620   Jarque-Bera (JB):                0.492
Skew:                           0.069   Prob(JB):                        0.782
Kurtosis:                       3.308   Cond. No.                     5.48e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.48e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [78]:
crsp_model_vola_lag = smf.ols("NGDP ~ year + qtr + qtr_vola_lag", train_crsp_macro).fit()
print(crsp_model_vola_lag.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                  0.258
Method:                 Least Squares   F-statistic:                     8.085
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           2.08e-06
Time:                        02:46:30   Log-Likelihood:                -230.27
No. Observations:                 103   AIC:                             472.5
Df Residuals:                      97   BIC:                             488.4
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      150.7093     62.827      2.399      0.018      26.015     275.404
qtr[T.Q2]        1.2658      0.654      1.934      0.056      -0.033       2.565
qtr[T.Q3]        0.4407      0.656      0.672      0.503      -0.861       1.742
qtr[T.Q4]        0.5408      0.653      0.827      0.410      -0.756       1.838
year            -0.0722      0.031     -2.298      0.024      -0.135      -0.010
qtr_vola_lag  -217.8787     43.818     -4.972      0.000    -304.844    -130.913
==============================================================================
Omnibus:                       10.594   Durbin-Watson:                   1.591
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               17.947
Skew:                          -0.398   Prob(JB):                     0.000127
Kurtosis:                       4.883   Cond. No.                     5.54e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.54e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [79]:
crsp_model_index = smf.ols("NGDP ~ year + qtr + qtr_idx_level", train_crsp_macro).fit()
print(crsp_model_index.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.200
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     4.909
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           0.000473
Time:                        02:46:30   Log-Likelihood:                -239.84
No. Observations:                 104   AIC:                             491.7
Df Residuals:                      98   BIC:                             507.6
Df Model:                           5
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept       663.8994    154.725      4.291      0.000     356.854     970.945
qtr[T.Q2]         1.2429      0.694      1.791      0.076      -0.135       2.620
qtr[T.Q3]         0.5325      0.694      0.767      0.445      -0.845       1.910
qtr[T.Q4]         0.2304      0.697      0.331      0.742      -1.153       1.614
year             -0.3312      0.078     -4.260      0.000      -0.485      -0.177
qtr_idx_level     0.0012      0.000      3.168      0.002       0.000       0.002
==============================================================================
Omnibus:                       17.053   Durbin-Watson:                   1.198
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.746
Skew:                          -0.794   Prob(JB):                     6.97e-06
Kurtosis:                       4.719   Cond. No.                     2.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [80]:
crsp_model_index_lag = smf.ols("NGDP ~ year + qtr + qtr_idx_level_lag", train_crsp_macro).fit()
print(crsp_model_index_lag.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.141
Model:                            OLS   Adj. R-squared:                  0.097
Method:                 Least Squares   F-statistic:                     3.192
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0104
Time:                        02:46:30   Log-Likelihood:                -240.37
No. Observations:                 103   AIC:                             492.7
Df Residuals:                      97   BIC:                             508.5
Df Model:                           5
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept           456.3901    160.177      2.849      0.005     138.483     774.297
qtr[T.Q2]             1.4115      0.721      1.958      0.053      -0.020       2.843
qtr[T.Q3]             0.6416      0.722      0.889      0.376      -0.791       2.075
qtr[T.Q4]             0.5287      0.722      0.733      0.465      -0.903       1.961
year                 -0.2269      0.080     -2.820      0.006      -0.387      -0.067
qtr_idx_level_lag     0.0007      0.000      1.749      0.084   -9.74e-05       0.002
==============================================================================
Omnibus:                       29.211   Durbin-Watson:                   1.180
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               62.080
Skew:                          -1.088   Prob(JB):                     3.31e-14
Kurtosis:                       6.119   Cond. No.                     2.26e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.26e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [81]:
crsp_model_inc_ret = smf.ols("NGDP ~ year + qtr + qtr_income_ret", train_crsp_macro).fit()
print(crsp_model_inc_ret.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.201
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     4.930
Date:                Wed, 04 Mar 2026   Prob (F-statistic):           0.000456
Time:                        02:46:30   Log-Likelihood:                -239.80
No. Observations:                 104   AIC:                             491.6
Df Residuals:                      98   BIC:                             507.5
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        300.7750     70.240      4.282      0.000     161.385     440.165
qtr[T.Q2]          1.3527      0.694      1.950      0.054      -0.024       2.729
qtr[T.Q3]          0.6199      0.694      0.894      0.374      -0.757       1.997
qtr[T.Q4]          0.7227      0.699      1.034      0.304      -0.665       2.110
year              -0.1468      0.035     -4.204      0.000      -0.216      -0.077
qtr_income_ret  -545.6502    171.485     -3.182      0.002    -885.957    -205.343
==============================================================================
Omnibus:                       21.516   Durbin-Watson:                   1.171
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               35.655
Skew:                          -0.895   Prob(JB):                     1.81e-08
Kurtosis:                       5.241   Cond. No.                     1.42e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.42e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [82]:
crsp_model_inc_ret_lag = smf.ols("NGDP ~ year + qtr + qtr_income_ret_lag", train_crsp_macro).fit()
print(crsp_model_inc_ret_lag.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.164
Model:                            OLS   Adj. R-squared:                  0.120
Method:                 Least Squares   F-statistic:                     3.793
Date:                Wed, 04 Mar 2026   Prob (F-statistic):            0.00351
Time:                        02:46:30   Log-Likelihood:                -239.02
No. Observations:                 103   AIC:                             490.0
Df Residuals:                      97   BIC:                             505.8
Df Model:                           5
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            266.8657     72.516      3.680      0.000     122.942     410.789
qtr[T.Q2]              1.2238      0.718      1.705      0.091      -0.201       2.648
qtr[T.Q3]              0.5266      0.716      0.736      0.464      -0.894       1.947
qtr[T.Q4]              0.4010      0.716      0.560      0.577      -1.020       1.822
year                  -0.1301      0.036     -3.613      0.000      -0.202      -0.059
qtr_income_ret_lag  -417.1866    174.442     -2.392      0.019    -763.406     -70.968
==============================================================================
Omnibus:                       31.691   Durbin-Watson:                   1.255
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               74.449
Skew:                          -1.136   Prob(JB):                     6.82e-17
Kurtosis:                       6.491   Cond. No.                     1.42e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.42e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

Insights: average firm count is statistically insignificant to the Nominal GDP

In [83]:
crsp_model_firm_cnt = smf.ols("NGDP ~ year + qtr + avg_firm_count", train_crsp_macro).fit()
print(crsp_model_firm_cnt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.119
Model:                            OLS   Adj. R-squared:                  0.074
Method:                 Least Squares   F-statistic:                     2.645
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0275
Time:                        02:46:30   Log-Likelihood:                -244.89
No. Observations:                 104   AIC:                             501.8
Df Residuals:                      98   BIC:                             517.6
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        264.3963    205.705      1.285      0.202    -143.818     672.611
qtr[T.Q2]          1.3067      0.728      1.794      0.076      -0.139       2.752
qtr[T.Q3]          0.5764      0.729      0.791      0.431      -0.870       2.023
qtr[T.Q4]          0.4613      0.733      0.629      0.531      -0.993       1.916
year              -0.1045      0.037     -2.815      0.006      -0.178      -0.031
avg_firm_count    -0.1021      0.444     -0.230      0.819      -0.984       0.780
==============================================================================
Omnibus:                       34.970   Durbin-Watson:                   1.137
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               86.898
Skew:                          -1.229   Prob(JB):                     1.35e-19
Kurtosis:                       6.744   Cond. No.                     1.65e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [84]:
crsp_model_firm_cnt_lag = smf.ols("NGDP ~ year + qtr + avg_firm_count_lag", train_crsp_macro).fit()
print(crsp_model_firm_cnt_lag.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   NGDP   R-squared:                       0.114
Model:                            OLS   Adj. R-squared:                  0.069
Method:                 Least Squares   F-statistic:                     2.505
Date:                Wed, 04 Mar 2026   Prob (F-statistic):             0.0353
Time:                        02:46:30   Log-Likelihood:                -241.96
No. Observations:                 103   AIC:                             495.9
Df Residuals:                      97   BIC:                             511.7
Df Model:                           5
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            238.4854    301.012      0.792      0.430    -358.941     835.911
qtr[T.Q2]              1.4541      0.732      1.987      0.050       0.001       2.907
qtr[T.Q3]              0.7216      0.732      0.985      0.327      -0.732       2.175
qtr[T.Q4]              0.5980      0.734      0.815      0.417      -0.858       2.054
year                  -0.0977      0.038     -2.605      0.011      -0.172      -0.023
avg_firm_count_lag    -0.0779      0.643     -0.121      0.904      -1.355       1.199
==============================================================================
Omnibus:                       35.874   Durbin-Watson:                   1.132
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.245
Skew:                          -1.255   Prob(JB):                     9.32e-21
Kurtosis:                       6.897   Cond. No.                     2.41e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.41e+06. This might indicate that there are
strong multicollinearity or other numerical problems.